unit UMain;

{$mode objfpc}{$H+}

{ =============================================================================
  UMain — Modbus RTU Sniffer main form
  =============================================================================

  DISCLAIMER: All documentation was generated by Antropic's Claude Sonnet 4.6

  PURPOSE
  ───────
  This unit implements the entire GUI for the Modbus RTU Sniffer.  It owns the
  serial port (via LazSerial1), the frame assembler (TModbusAssembler), all
  packet storage, and every user-facing control.

  ARCHITECTURE OVERVIEW
  ──────────────────────

    ┌────────────────────────────────────────────────────────────┐
    │  LazSerial1 (background reader thread, managed by LazSerial│
    │  — fires OnRxData on the main thread via Synchronize)      │
    └───────────────────────┬────────────────────────────────────┘
                            │ LazSerial1.ReadData → string of raw bytes
                            ▼
    ┌────────────────────────────────────────────────────────────┐
    │  FAssembler  (TModbusAssembler)                            │
    │  • PushBytes() accumulates bytes into an internal ring buf │
    │  • On each push, scans for the shortest suffix whose CRC-16│
    │    matches → emits a TModbusPacket via OnPacket callback   │
    │  • Flush() forces emission of whatever is buffered (called │
    │    on inter-frame gap timeout and on Stop)                 │
    └───────────────────────┬────────────────────────────────────┘
                            │ OnPacketReady(APkt)  — main thread
                            ▼
    ┌────────────────────────────────────────────────────────────┐
    │  FPackets / FFiltered  (TList)                             │
    │  • FPackets owns every TModbusPacket (up to 10 000)        │
    │  • FFiltered holds non-owning refs to the matching subset  │
    │  • FPendingRows counts packets not yet written to strgMain │
    └───────────────────────┬────────────────────────────────────┘
                            │ FTimerStats fires every 1 s
                            ▼
    ┌────────────────────────────────────────────────────────────┐
    │  strgMain  (TStringGrid, 9 columns, custom DrawCell)       │
    │  • Rows appended in one BeginUpdate/EndUpdate block        │
    │  • TModbusPacket pointer stored in Objects[0,row] for O(1) │
    │    colour lookup in strgMainDrawCell                       │
    └────────────────────────────────────────────────────────────┘

  THREADING
  ─────────
  LazSerial's reader thread calls OnRxData via Synchronize, so
  LazSerial1RxData always executes on the main (VCL/LCL) thread.
  No explicit locking is needed anywhere in this unit.

  INTER-FRAME GAP DETECTION
  ──────────────────────────
  Modbus RTU defines a frame boundary as a silence of ≥ 3.5 character times.
  FTimerFrame is restarted on every OnRxData call.  When it fires it means no
  bytes have arrived for at least one frame gap, so FAssembler.Flush() is
  called to emit whatever partial data is buffered.  The interval is calculated
  from the configured baud rate in CalcFrameTimeout.

  GRID UPDATE STRATEGY
  ────────────────────
  Packets arrive potentially hundreds of times per second.  Writing to
  TStringGrid on every packet would saturate the paint queue and freeze the UI
  (the bug this design was created to fix).  Instead:

    1. OnPacketReady stores the packet and increments FPendingRows only.
       Zero grid work happens here.
    2. TimerStatsTimer fires every 1 second and calls UpdateStats.
    3. UpdateStats appends all FPendingRows in a single BeginUpdate/EndUpdate
       block, setting RowCount once and then filling cells by index.  This
       causes exactly one repaint regardless of how many packets arrived.

  PACKET CAP
  ──────────
  FPackets is capped at 10 000 entries.  When the cap is reached the oldest
  packet is freed and deleted, and RebuildGrid rewrites the entire grid with
  renumbered rows.  This is intentionally rare (every 10 000 packets) and
  unavoidable because row numbers shift.

  ============================================================================= }

interface

uses
  Classes,    { TList, TTimer }
  SysUtils,   { Format, IntToStr, … }
  StrUtils,   { AnsiContainsText (indirect — kept for future use) }
  Forms,      { TForm, Application }
  Controls,   { TControl, TWinControl }
  Graphics,   { TColor, TFont, … }
  Dialogs,    { ShowMessage, TSaveDialog }
  ExtCtrls,   { TPanel, TTimer }
  Buttons,    { TBitBtn, TSpeedButton }
  StdCtrls,   { TLabel, TEdit, TCheckBox, TMemo, TGroupBox }
  Grids,      { TStringGrid, TTextStyle, TGridDrawState }
  LazSerial,  { TLazSerial, TBaudRate, ConstsBaud }
  DateUtils,  { MilliSecondsBetween }
  LCLIntf,    { InflateRect }
  LCLType,    { TRect }
  UAboutBox,  { Aboutbox }
  UModbusTypes,   { TModbusPacket, GetFunctionName, GetExceptionName }
  UModbusSniffer; { TModbusAssembler }

type

  { TfrmMain
    ─────────
    The application's single form.  All fields prefixed with F are private
    state; all published fields are form components placed by the IDE. }

  TfrmMain = class(TForm)
    btnInfo: TBitBtn;

    { ── Toolbar buttons ───────────────────────────────────────────────────── }
    btnStart:        TBitBtn;   { Opens the serial port and begins capture    }
    btnStop:         TBitBtn;   { Closes the port and halts capture           }
    btnClear:        TBitBtn;   { Frees all packets and clears the grid       }
    btnExport:       TBitBtn;   { Saves visible packets to a CSV file         }
    btnCommConfig:   TBitBtn;   { Opens LazSerial's built-in setup dialog     }

    { ── Filter / option controls ──────────────────────────────────────────── }
    chkbAutoScroll:  TCheckBox;   { When checked, grid scrolls to newest row  }
    chkbShowHex:     TCheckBox;   { Toggles the Hex column (COL_HEX) on/off  }
    edtFilter:       TEdit;       { Live filter text — matched against every  }
                                  { packet field on each keystroke            }
    sbtnClearFilter: TSpeedButton;{ Clears edtFilter and removes the filter   }
    lblFilter:       TLabel;      { Static "Filter:" label                    }

    { ── Layout panels ─────────────────────────────────────────────────────── }
    pnlToolBar:         TPanel; { Top bar: action buttons + port controls     }
    pnlFilterBar:       TPanel; { Second bar: filter input + display options  }
    pnlStatusBar:       TPanel; { Live stats: packets, errors, rate, count    }
    pnlBottomStatusBar: TPanel; { Port status / ready / monitoring message    }
    pnlDetails:         TPanel; { Right panel hosting grpPacketDetails        }
    pnlMain:            TPanel; { Central area hosting strgMain               }

    { ── Main data grid ────────────────────────────────────────────────────── }
    strgMain: TStringGrid;
    { 9 columns (see COL_* constants):
        0  #         – global packet number (1-based)
        1  Time      – HH:MM:SS.mmm timestamp
        2  Dir       – TX or RX
        3  Addr      – slave address in hex (0x01 … 0xFF)
        4  Func      – function code in hex (0x01 … 0x17)
        5  Len       – total frame length in bytes
        6  CRC       – "OK" or "BAD"
        7  Hex       – full frame as space-separated hex bytes (hideable)
        8  Description – parsed human-readable summary
      Row 0 is the fixed header.  Rows 1..N contain data.
      strgMain.Objects[0, row] stores the TModbusPacket pointer for that row
      so strgMainDrawCell can colour the row in O(1) without a list lookup. }

    { ── Serial port component ─────────────────────────────────────────────── }
    grpPacketDetails: TGroupBox;
    { Hosts a dynamically created TMemo that shows the full breakdown of the
      selected packet.  The memo is recreated each time a row is selected to
      avoid managing state across selections. }

    LazSerial1: TLazSerial;
    { The serial port component.  Configuration (device, baud, parity, etc.)
      is set by the user via LazSerial1.ShowSetupDialog (btnCommConfig).
      LazSerial1.OnRxData is wired to LazSerial1RxData at Start time.
      ConstsBaud[LazSerial1.BaudRate] converts the TBaudRate enum to an
      integer for display and timeout calculations. }

    { ── Form lifecycle ────────────────────────────────────────────────────── }
    procedure btnInfoClick(Sender: TObject);
    procedure FormCreate(Sender: TObject);
    { Allocates FPackets, FFiltered, FAssembler, FTimerFrame, FTimerStats.
      Calls SetupGrid, SetControlsRunning(False), ClearDetails, and sets the
      initial status bar text. }

    procedure FormDestroy(Sender: TObject);
    { Stops the sniffer if running, then frees FAssembler, FFiltered, and
      all TModbusPacket objects owned by FPackets. }

    procedure FormCloseQuery(Sender: TObject; var CanClose: Boolean);
    { Ensures the port is closed before the form is destroyed. }

    { ── Button events ─────────────────────────────────────────────────────── }
    procedure btnStartClick(Sender: TObject);
    { Validates that a port is configured, wires LazSerial1.OnRxData,
      opens the port, calculates the frame timeout, and starts FTimerStats. }

    procedure btnStopClick(Sender: TObject);
    { Disables both timers, flushes the assembler, closes the serial port,
      and updates the UI to the "Stopped" state. }

    procedure btnClearClick(Sender: TObject);
    { Resets the grid to header-only, frees all owned packets, clears
      FFiltered, resets all counters, and calls ClearDetails + UpdateStats. }

    procedure btnExportClick(Sender: TObject);
    { Presents a TSaveDialog, then writes either FFiltered (if filter is
      active) or FPackets to a CSV file via BuildCSVLine. }

    procedure btnCommConfigClick(Sender: TObject);
    { Calls LazSerial1.ShowSetupDialog (LazSerial's built-in modal config
      dialog).  Updates pnlBottomStatusBar with the chosen port and baud. }

    { ── Filter / option events ────────────────────────────────────────────── }
    procedure edtFilterChange(Sender: TObject);
    { Fires on every keystroke.  Resets FPendingRows, calls ApplyFilter to
      rebuild FFiltered, then calls RebuildGrid for an immediate full repaint. }

    procedure sbtnClearFilterClick(Sender: TObject);
    { Sets edtFilter.Text := '' which triggers edtFilterChange, clearing
      the filter and showing all packets. }

    procedure chkbShowHexChange(Sender: TObject);
    { Shows or hides COL_HEX by setting its ColWidth to 180 or 0. }

    { ── Grid events ───────────────────────────────────────────────────────── }
    procedure strgMainSelectCell(Sender: TObject; ACol, ARow: Integer;
                                  var CanSelect: Boolean);
    { Called when the user clicks a data row (ARow ≥ 1).  Calls
      ShowPacketDetails with the TModbusPacket at that row. }

    procedure strgMainDrawCell(Sender: TObject; ACol, ARow: Integer;
                                Rect: TRect; State: TGridDrawState);
    { Owner-draw handler for every cell.
      Row 0: dark header background, bold centred text.
      Rows 1+: background and foreground chosen from the BG_*/FG_* palette
               based on the packet type stored in Objects[0, ARow]:
                 gdSelected        → BG_SEL  / clWhite
                 IsException       → BG_EX   / FG_EX   (dark red / red)
                 not ValidCRC      → BG_BADC / FG_BADC  (dark magenta / magenta)
                 Direction = 'TX'  → BG_NORMAL / FG_TX  (dark bg / blue)
                 Direction = 'RX'  → BG_NORMAL / FG_RX  (dark bg / green)
      Column alignment: right for #/Len, centred for Dir/CRC, left elsewhere.
      InflateRect(-2, 0) adds a small horizontal margin before TextRect. }

    { ── Serial / timer events ─────────────────────────────────────────────── }
    procedure LazSerial1RxData(Sender: TObject);
    { Fired by LazSerial on the main thread when bytes are available.
      Resets FTimerFrame (restarts the inter-frame gap countdown) then
      calls FAssembler.PushBytes(LazSerial1.ReadData) to hand all buffered
      bytes to the assembler. }

    procedure TimerFrameTimer(Sender: TObject);
    { Fires when no bytes have arrived for ≥ 1 frame gap (FTimerFrame.Interval).
      Disables itself then calls FAssembler.Flush to emit any partial frame
      that the CRC scanner hasn't claimed yet. }

    procedure TimerStatsTimer(Sender: TObject);
    { Fires every 1 second.  Delegates entirely to UpdateStats which both
      flushes FPendingRows to the grid and refreshes pnlStatusBar. }

  private

    { ── Core objects ── }

    FAssembler: TModbusAssembler;
    { Stateful byte-stream-to-frame converter.  Owned by this form.
      Thread-safe note: only touched from the main thread (OnRxData is
      Synchronized by LazSerial). }

    FTimerFrame: TTimer;
    { Inter-frame gap detector.  Interval set by CalcFrameTimeout using the
      formula:  Max(2 ms,  Round(11 × 3.5 × 1000 / baud))
      Restarted on every OnRxData call; fires Flush when no bytes arrive
      for one full gap period. }

    FTimerStats: TTimer;
    { Drives all grid updates (see GRID UPDATE STRATEGY above) and refreshes
      the statistics panel.  Enabled only while FRunning = True. }

    FRunning: Boolean;
    { True between btnStartClick and btnStopClick.  Guards calls that depend
      on the port being open (e.g. pnlBottomStatusBar caption formatting). }

    { ── Packet storage ── }

    FPackets: TList;
    { Owns all TModbusPacket objects captured since the last Clear.
      Capped at 10 000 entries; oldest is freed when the cap is exceeded. }

    FFiltered: TList;
    { Non-owning subset of FPackets that matches the current filter text.
      Rebuilt by ApplyFilter.  Empty (and ignored) when FFilterActive = False. }

    FFilterActive: Boolean;
    { True when edtFilter.Text is non-empty after trimming.
      Controls whether FPackets or FFiltered is the display source. }

    FFilterText: string;
    { Trimmed, lowercase copy of edtFilter.Text used by PacketMatchesFilter. }

    { ── Statistics ── }

    FPacketCount: Integer;
    { Total packets received since last Clear, including filtered-out ones. }

    FErrorCount: Integer;
    { Packets with IsException=True OR ValidCRC=False since last Clear. }

    FLastCount: Integer;
    { Value of FPacketCount at the previous stats update, used to calculate
      the per-second rate as (FPacketCount - FLastCount) / elapsed. }

    FLastStatTime: TDateTime;
    { TDateTime of the previous stats update.  Combined with FLastCount to
      compute the rolling packet rate displayed in pnlStatusBar. }

    { ── Grid batching ── }

    FPendingRows: Integer;
    { Number of packets added to FPackets (or FFiltered) since the last grid
      flush.  Incremented by OnPacketReady; reset to 0 after UpdateStats
      writes the rows.  Ensures the grid is updated at most once per timer
      tick regardless of how many packets arrived. }

    { ── Private methods ── }

    procedure SetupGrid;
    { Called once from FormCreate.  Configures strgMain: column count, fixed
      row, column widths, header captions, font, colours, and event handlers.
      Also hides COL_HEX if chkbShowHex is unchecked. }

    procedure SetControlsRunning(AOn: Boolean);
    { Enables/disables btnStart, btnStop, and btnCommConfig based on whether
      capture is running.  Prevents starting twice or stopping when idle. }

    procedure CalcFrameTimeout;
    { Computes FTimerFrame.Interval from the current baud rate.
      Formula: Max(2,  Round(11.0 × 3.5 × 1000.0 / baud))  [milliseconds]
      11 bits/char × 3.5 chars × 1000 ms/s ÷ baud rate.
      Minimum 2 ms to avoid busy-looping at very high baud rates. }

    procedure OnPacketReady(APkt: TModbusPacket);
    { Assembler callback — executes on the main thread (no locking needed).
      Adds APkt to FPackets (freeing the oldest if the 10 000 cap is reached),
      increments FPacketCount and FErrorCount, adds to FFiltered if the filter
      is active and the packet matches, then increments FPendingRows.
      No grid writes happen here. }

    procedure ApplyFilter;
    { Clears FFiltered and repopulates it by iterating FPackets and calling
      PacketMatchesFilter with the current FFilterText.  O(n) in packet count.
      Called by edtFilterChange (on every keystroke) and never during capture
      for incoming packets (those are matched inline in OnPacketReady). }

    function PacketMatchesFilter(APkt: TModbusPacket;
                                  const ALower: string): Boolean;
    { Returns True if ALower (already lowercased) matches any field of APkt.
      Fields checked in order:
        1. HexString     – space-separated hex bytes
        2. Address       – decimal integer
        3. FunctionCode  – decimal and 2-digit hex
        4. Direction     – "tx" or "rx"
        5. Description   – parsed text
        6. Timestamp     – HH:MM:SS.mmm
        7. HexString     – with spaces stripped (for patterns like "0306")
      Special keywords (case-insensitive):
        "tx" / "transmit" / "send"      → Direction = 'TX'
        "rx" / "receive"  / "recv"      → Direction = 'RX'
        "error" / "exception" / "invalid" → IsException or bad CRC
        "read"                           → FC 01–04
        "write"                          → FC 05, 06, 0F, 10          }

    procedure AddRowToGrid(APkt: TModbusPacket; AGlobalNum: Integer);
    { Appends one row to strgMain by incrementing RowCount and writing the
      nine cell values plus Objects[0] = APkt.
      Caller MUST wrap calls in strgMain.BeginUpdate / EndUpdate to prevent
      a repaint per row.  Only used during RebuildGrid (not during normal
      streaming — UpdateStats writes rows directly by index for efficiency). }

    procedure RebuildGrid;
    { Full grid rewrite.  Used when:
        • The filter changes (edtFilterChange)
        • The 10 000-packet cap rolls over (OnPacketReady)
      Pre-sizes RowCount to 1 + Src.Count to avoid N reallocations, then
      fills all cells by index inside a single BeginUpdate/EndUpdate block.
      Resets FPendingRows to 0 and scrolls to the last row if auto-scroll
      is on. }

    procedure UpdateStats;
    { Called every second by TimerStatsTimer.  Two responsibilities:

      1. GRID FLUSH: if FPendingRows > 0, extends strgMain.RowCount by
         FPendingRows and fills the new rows from the tail of FPackets
         (or FFiltered) inside one BeginUpdate/EndUpdate.  Resets
         FPendingRows and optionally scrolls to the last row.

      2. STATS LABEL: if ≥ 1 second has elapsed since FLastStatTime,
         recalculates the packet rate and updates pnlStatusBar.Caption. }

    procedure ShowPacketDetails(APkt: TModbusPacket);
    { Removes all controls from grpPacketDetails, creates a fresh TMemo
      (dark background, Consolas 9pt), and populates it with:
        Timestamp, Direction, Length, Device Address, Function Code,
        Exception (if any), CRC validity, Full Hex dump, Raw Bytes
        (16 per line), Data Bytes (16 per line), Description.
      The memo is read-only with a vertical scrollbar. }

    procedure ClearDetails;
    { Removes all controls from grpPacketDetails and places a placeholder
      TLabel ("Select a packet to view details"). }

    function PacketAtRow(ARow: Integer): TModbusPacket;
    { Maps a grid row index (1-based) to a TModbusPacket.
      Returns nil for the header row (ARow = 0) or out-of-range indices.
      Source is FFiltered when FFilterActive, else FPackets. }

    function BuildCSVLine(APkt: TModbusPacket): string;
    { Formats one CSV record from APkt.  Columns match the grid: Timestamp,
      Direction, Address (decimal), Function (hex), Length, CRC Valid
      (true/false), Hex Data, Description.  Embedded double-quotes in
      Description are replaced with single quotes; CR/LF stripped. }

  end;

var
  frmMain: TfrmMain;
  { Single global instance created by the LCL Application object. }

implementation

{$R *.lfm}

uses
  Clipbrd,  { Clipboard (reserved for future copy-row feature) }
  Math;     { Max() used in CalcFrameTimeout }

{ ── Column index constants ─────────────────────────────────────────────────
  These map column positions to semantic names throughout the unit.
  Changing a value here automatically updates every reference. }
const
  COL_NUM  = 0; { Sequential packet number (1-based, global across filter) }
  COL_TIME = 1; { Capture timestamp HH:MM:SS.mmm                          }
  COL_DIR  = 2; { "TX" (master→slave) or "RX" (slave→master)             }
  COL_ADDR = 3; { Modbus slave address 0x01–0xFF                          }
  COL_FUNC = 4; { Modbus function code 0x01–0x17 (or exception 0x81+)    }
  COL_LEN  = 5; { Total frame length including address, func, CRC bytes  }
  COL_CRC  = 6; { "OK" = CRC matches; "BAD" = CRC mismatch              }
  COL_HEX  = 7; { Full frame bytes as "AA BB CC …" (hideable)           }
  COL_DESC = 8; { Human-readable parse result from UModbusParser         }

{ ── Row colour palette ─────────────────────────────────────────────────────
  All colours are BGR not RGB (Windows COLORREF convention used by LCL).
  BG_ = background colour, FG_ = foreground (text) colour. }
const
  BG_NORMAL = $001E1E1E; { Default dark background for all data rows      }
  FG_TX     = $006699CC; { Blue text for TX (master request) rows         }
  FG_RX     = $004EC994; { Green text for RX (slave response) rows        }
  FG_EX     = $000000CC; { Red text for exception response rows           }
  FG_BADC   = $00AA00AA; { Magenta text for bad-CRC rows                  }
  BG_EX     = $001A0000; { Very dark red background for exceptions        }
  BG_BADC   = $001A001A; { Very dark magenta background for bad CRC       }
  BG_SEL    = $00944700; { Orange-ish highlight for the selected row      }

{ =============================================================================
  FormCreate / Destroy
  ============================================================================= }

procedure TfrmMain.FormCreate(Sender: TObject);
{ Initialises all private state in a defined order:
    1. Storage lists (must exist before any packet arrives)
    2. FAssembler (connects its OnPacket callback)
    3. FTimerFrame (disabled; interval set later in CalcFrameTimeout)
    4. FTimerStats (disabled; enabled only when capture is running)
    5. UI state (status labels, grid setup, button states, detail panel) }
begin

  frmMain.Caption:= APPLICATION_NAME + ' v. ' + VERSION_HISTORY[0].Version +
  ' (' + VERSION_HISTORY[0].Date  + ')';

  FPackets      := TList.Create;
  FFiltered     := TList.Create;
  FFilterActive := False;
  FFilterText   := '';
  FRunning      := False;
  FLastStatTime := Now;

  { Wire the assembler callback before any bytes can arrive }
  FAssembler          := TModbusAssembler.Create;
  FAssembler.OnPacket := @OnPacketReady;

  { Inter-frame gap timer — disabled until port is opened }
  FTimerFrame          := TTimer.Create(Self);
  FTimerFrame.Interval := 5;          { placeholder; CalcFrameTimeout refines }
  FTimerFrame.OnTimer  := @TimerFrameTimer;
  FTimerFrame.Enabled  := False;

  { Stats / grid-flush timer — 1 s tick, disabled until capture starts }
  FTimerStats          := TTimer.Create(Self);
  FTimerStats.Interval := 1000;
  FTimerStats.OnTimer  := @TimerStatsTimer;
  FTimerStats.Enabled  := False;

  { Initial status bar text }
  pnlBottomStatusBar.Color :=$00CC9966;
  pnlBottomStatusBar.Caption := 'Ready — click Comm Config to select port';
  pnlStatusBar.Caption :=
    'Packets: 0  |  Errors: 0  |  Rate: 0.0/s  |  Displaying: 0';

  SetupGrid;
  SetControlsRunning(False);
  ClearDetails;
end;

procedure TfrmMain.btnInfoClick(Sender: TObject);
{ Display about box with application description and version history }
begin
  ShowAboutBox;
end;

procedure TfrmMain.FormDestroy(Sender: TObject);
{ Frees all heap objects in reverse creation order.
  btnStopClick is called defensively in case the user closes the window
  without pressing Stop (FormCloseQuery also does this, but belt-and-braces). }
var
  I: Integer;
begin
  if FRunning then btnStopClick(nil);
  FreeAndNil(FAssembler);
  FFiltered.Free;                           { non-owning — just free the list }
  for I := 0 to FPackets.Count - 1 do
    TModbusPacket(FPackets[I]).Free;        { free each owned packet }
  FPackets.Free;
end;

procedure TfrmMain.FormCloseQuery(Sender: TObject; var CanClose: Boolean);
{ Ensures the serial port is closed before the OS handle is released.
  Always sets CanClose := True — no unsaved-data prompt needed. }
begin
  if FRunning then btnStopClick(nil);
  CanClose := True;
end;

{ =============================================================================
  Grid setup and custom drawing
  ============================================================================= }

procedure TfrmMain.SetupGrid;
{ Configures strgMain from scratch.  Called once from FormCreate.
  All visual properties (font, colours, column widths) are set here rather
  than in the .lfm so the grid appearance is self-contained in this unit. }
begin
  with strgMain do
  begin
    RowCount         := 1;          { header row only at startup }
    FixedRows        := 1;          { row 0 is always the header }
    FixedCols        := 0;          { no fixed columns }
    ColCount         := 9;
    Options          := Options
                        + [goRowSelect,      { whole-row selection }
                           goColSizing,       { user-resizable columns }
                           goThumbTracking]   { live resize feedback }
                        - [goEditing,         { read-only }
                           goAlwaysShowEditor];
    DefaultRowHeight := 18;
    RowHeights[0]    := 20;         { header slightly taller }

    { Column widths — COL_DESC intentionally wide for long descriptions }
    ColWidths[COL_NUM]  := 50;
    ColWidths[COL_TIME] := 88;
    ColWidths[COL_DIR]  := 36;
    ColWidths[COL_ADDR] := 46;
    ColWidths[COL_FUNC] := 46;
    ColWidths[COL_LEN]  := 36;
    ColWidths[COL_CRC]  := 40;
    ColWidths[COL_HEX]  := 180;
    ColWidths[COL_DESC] := 400;

    { Header captions written directly into row 0 }
    Cells[COL_NUM,  0] := '#';
    Cells[COL_TIME, 0] := 'Time';
    Cells[COL_DIR,  0] := 'Dir';
    Cells[COL_ADDR, 0] := 'Addr';
    Cells[COL_FUNC, 0] := 'Func';
    Cells[COL_LEN,  0] := 'Len';
    Cells[COL_CRC,  0] := 'CRC';
    Cells[COL_HEX,  0] := 'Hex';
    Cells[COL_DESC, 0] := 'Description';

    { Dark-theme colours }
    Color         := BG_NORMAL;     { cell background }
    Font.Color    := $00CCCCCC;     { default cell text }
    Font.Name     := 'Consolas';    { monospace for hex alignment }
    Font.Size     := 9;
    FixedColor    := $00262525;     { header row background }
    GridLineColor := $00333333;     { subtle grid lines }

    { Wire events programmatically (also set in .lfm, but explicit here
      so the connection is obvious when reading this unit) }
    OnDrawCell   := @strgMainDrawCell;
    OnSelectCell := @strgMainSelectCell;
  end;

  { Respect the initial state of the Show Hex checkbox }
  if not chkbShowHex.Checked then
    strgMain.ColWidths[COL_HEX] := 0;
end;

procedure TfrmMain.strgMainDrawCell(Sender: TObject; ACol, ARow: Integer;
                                     Rect: TRect; State: TGridDrawState);
{ Owner-draw handler.  Called for every visible cell on every repaint.
  Keep this fast — avoid any allocation or list lookup.
  The TModbusPacket pointer stored in Objects[COL_NUM, ARow] gives O(1)
  access to the packet for colour decisions. }
var
  APkt:   TModbusPacket;
  FG, BG: TColor;
  S:      string;
  TS:     TTextStyle;
begin
  with strgMain.Canvas do
  begin
    { ── Header row (row 0) ── }
    if ARow = 0 then
    begin
      Brush.Color := $00262525;
      Font.Color  := $00AAAAAA;
      Font.Style  := [fsBold];
      FillRect(Rect);
      S  := strgMain.Cells[ACol, ARow];
      TS := TextStyle;
      TS.Alignment  := taCenter;
      TS.Layout     := tlCenter;
      TS.SingleLine := True;
      TS.Clipping   := True;
      TextRect(Rect, Rect.Left, Rect.Top, S, TS);
      Font.Style := [];
      Exit;
    end;

    { ── Data rows ── }

    { Retrieve packet pointer — may be nil if the row was pre-allocated but
      not yet filled (should not happen in normal operation) }
    APkt := TModbusPacket(strgMain.Objects[COL_NUM, ARow]);

    { Determine background and foreground colours based on packet state.
      Priority: selection > exception > bad CRC > TX > RX (default) }
    if gdSelected in State then
      begin BG := BG_SEL;    FG := clWhite;  end
    else if (APkt <> nil) and APkt.IsException then
      begin BG := BG_EX;     FG := FG_EX;    end
    else if (APkt <> nil) and not APkt.ValidCRC then
      begin BG := BG_BADC;   FG := FG_BADC;  end
    else if (APkt <> nil) and (APkt.Direction = 'TX') then
      begin BG := BG_NORMAL; FG := FG_TX;    end
    else
      begin BG := BG_NORMAL; FG := FG_RX;    end;

    Brush.Color := BG;
    Font.Color  := FG;
    FillRect(Rect);

    { Draw cell text with column-appropriate alignment }
    S  := strgMain.Cells[ACol, ARow];
    TS := TextStyle;
    TS.SingleLine := True;
    TS.Clipping   := True;
    case ACol of
      COL_NUM, COL_LEN: TS.Alignment := taRightJustify;
      COL_DIR, COL_CRC: TS.Alignment := taCenter;
    else
      TS.Alignment := taLeftJustify;
    end;

    { Inset 2 px horizontally to avoid text touching grid lines }
    InflateRect(Rect, -2, 0);
    TextRect(Rect, Rect.Left, Rect.Top, S, TS);
  end;
end;

procedure TfrmMain.strgMainSelectCell(Sender: TObject; ACol, ARow: Integer;
                                       var CanSelect: Boolean);
{ Fires when the user clicks any cell.  ACol is ignored — the grid uses
  whole-row selection (goRowSelect).  Row 0 (header) is skipped. }
begin
  CanSelect := True;
  if ARow < 1 then Exit;
  ShowPacketDetails(PacketAtRow(ARow));
end;

{ =============================================================================
  Comm Config
  ============================================================================= }

procedure TfrmMain.btnCommConfigClick(Sender: TObject);
{ Delegates to LazSerial's own setup dialog which handles port enumeration,
  baud rate, parity, data bits, stop bits, and flow control.
  After the dialog closes, LazSerial1.Device and LazSerial1.BaudRate hold the
  chosen values.  ConstsBaud[] converts TBaudRate → Integer for display. }
begin
  LazSerial1.ShowSetupDialog;
  if LazSerial1.Device <> '' then
    pnlBottomStatusBar.Caption :=
      Format('Ready — %s @ %d baud',
        [LazSerial1.Device, ConstsBaud[LazSerial1.BaudRate]])
  else
    pnlBottomStatusBar.Caption := 'Ready — click Comm Config to select port';
end;

{ =============================================================================
  Start / Stop
  ============================================================================= }

procedure TfrmMain.CalcFrameTimeout;
{ Sets FTimerFrame.Interval to the Modbus RTU inter-frame gap for the current
  baud rate.  The gap is 3.5 character times; one character is 11 bits
  (1 start + 8 data + 1 parity/stop + 1 stop).

  Formula:  interval_ms = max(2,  round(11 × 3.5 × 1000 / baud))

  Examples:
    9 600 baud → 4.0 ms  → 4 ms
   19 200 baud → 2.0 ms  → 2 ms
  115 200 baud → 0.33 ms → 2 ms  (minimum enforced) }
var
  Baud, Ms: Integer;
begin
  Baud := ConstsBaud[LazSerial1.BaudRate];
  if Baud <= 0 then Baud := 9600;
  Ms := Max(2, Round(11.0 * 3.5 * 1000.0 / Baud));
  FTimerFrame.Interval := Ms;
end;

procedure TfrmMain.btnStartClick(Sender: TObject);
{ Opens the serial port and begins capture.
  Guard: rejects start if no device is configured (would throw on LazSerial1.Open).
  Wires LazSerial1.OnRxData here rather than in FormCreate so that no events
  fire before the user deliberately starts capture. }
begin
  if LazSerial1.Device = '' then
  begin
    ShowMessage('Please configure the serial port first (Comm Config).');
    Exit;
  end;

  LazSerial1.OnRxData := @LazSerial1RxData;

  try
    LazSerial1.Open;
  except
    on E: Exception do
    begin
      ShowMessage('Failed to open port: ' + E.Message);
      Exit;
    end;
  end;

  FRunning      := True;
  FPacketCount  := 0;
  FErrorCount   := 0;
  FLastCount    := 0;
  FLastStatTime := Now;

  CalcFrameTimeout;             { set frame gap based on actual baud rate }
  FTimerStats.Enabled := True;  { start 1 s tick for grid flush + stats }

  SetControlsRunning(True);
  pnlBottomStatusBar.Caption :=
    Format('Monitoring %s @ %d baud',
      [LazSerial1.Device, ConstsBaud[LazSerial1.BaudRate]]);
end;

procedure TfrmMain.btnStopClick(Sender: TObject);
{ Halts capture in a clean shutdown sequence:
    1. Clear FRunning flag so no new stat updates reference the port.
    2. Disable both timers (prevents TimerFrameTimer firing after close).
    3. Flush the assembler to emit any bytes that arrived just before stop.
    4. Close the serial port — releases the OS handle.
    5. Update UI state. }
begin
  FRunning            := False;
  FTimerFrame.Enabled := False;
  FTimerStats.Enabled := False;

  FAssembler.Flush;           { emit any buffered partial frame }

  if LazSerial1.Active then
    LazSerial1.Close;

  SetControlsRunning(False);
  pnlBottomStatusBar.Caption := 'Stopped';
end;

{ =============================================================================
  Serial receive path
  ============================================================================= }

procedure TfrmMain.LazSerial1RxData(Sender: TObject);
{ Hot path — called on the main thread by LazSerial (via Synchronize) every
  time the OS signals that bytes are available in the UART receive buffer.
  This should be as fast as possible:
    • Restart FTimerFrame (one boolean write + TTimer reset).
    • Hand the bytes to FAssembler (copies into a fixed-size ring buffer). }
begin
  { Restart inter-frame gap countdown on every byte arrival }
  FTimerFrame.Enabled := False;
  FTimerFrame.Enabled := True;

  FAssembler.PushBytes(LazSerial1.ReadData);
end;

procedure TfrmMain.TimerFrameTimer(Sender: TObject);
{ Fires when the inter-frame gap has expired (no bytes for ≥ 1 frame time).
  Disables itself first to prevent repeat firing, then calls Flush.
  Flush emits whatever bytes are in the assembler buffer as a frame, even
  if no valid CRC was found — useful for capturing corrupt or short frames. }
begin
  FTimerFrame.Enabled := False;
  FAssembler.Flush;
end;

{ =============================================================================
  Assembler callback
  ============================================================================= }

procedure TfrmMain.OnPacketReady(APkt: TModbusPacket);
{ Called by FAssembler (on the main thread) for each complete Modbus frame.
  APkt is freshly allocated by the assembler and its ownership transfers here.

  Design note: NO grid writes happen in this procedure.  Writing to
  TStringGrid on every packet (potentially hundreds per second at 115200 baud)
  saturates the LCL paint queue and freezes the UI.  Instead, FPendingRows is
  incremented and UpdateStats flushes all pending rows in a single batch
  once per second. }
begin
  { Enforce the 10 000-packet cap.  FPackets[0] is the oldest. }
  if FPackets.Count >= 10000 then
  begin
    TModbusPacket(FPackets[0]).Free;
    FPackets.Delete(0);
    { All row numbers have shifted by -1, so a full grid rebuild is required.
      This is unavoidable but happens at most once every 10 000 packets. }
    RebuildGrid;
  end;

  FPackets.Add(APkt);
  Inc(FPacketCount);
  if APkt.IsException or not APkt.ValidCRC then
    Inc(FErrorCount);

  if FFilterActive then
  begin
    { Only add to FFiltered (and count as a pending row) if it matches }
    if PacketMatchesFilter(APkt, LowerCase(FFilterText)) then
    begin
      FFiltered.Add(APkt);
      Inc(FPendingRows);
    end;
    { Non-matching packets are stored in FPackets but not displayed until
      the filter is cleared or changed. }
  end
  else
    Inc(FPendingRows);  { no filter — every packet is a pending grid row }
end;

{ =============================================================================
  Grid population
  ============================================================================= }

function TfrmMain.PacketAtRow(ARow: Integer): TModbusPacket;
{ Translates a 1-based grid row index to a TModbusPacket reference.
  Row 0 is the header; rows 1..N map to indices 0..N-1 in the source list.
  Returns nil for the header row or any out-of-range index. }
var
  Idx: Integer;
begin
  Result := nil;
  Idx    := ARow - 1;   { convert to 0-based list index }
  if FFilterActive then
  begin
    if (Idx >= 0) and (Idx < FFiltered.Count) then
      Result := TModbusPacket(FFiltered[Idx]);
  end
  else
  begin
    if (Idx >= 0) and (Idx < FPackets.Count) then
      Result := TModbusPacket(FPackets[Idx]);
  end;
end;

procedure TfrmMain.AddRowToGrid(APkt: TModbusPacket; AGlobalNum: Integer);
{ Appends one data row to strgMain.
  IMPORTANT: caller must bracket any loop of AddRowToGrid calls with
  strgMain.BeginUpdate / EndUpdate.  Each RowCount increment triggers a
  layout recalculation; without batching, N calls cause N repaints.
  Used only by RebuildGrid — normal streaming uses UpdateStats which
  writes cells by pre-computed index without touching RowCount in a loop. }
var
  R: Integer;
begin
  R := strgMain.RowCount;
  strgMain.RowCount := R + 1;
  strgMain.Cells[COL_NUM,  R] := IntToStr(AGlobalNum);
  strgMain.Cells[COL_TIME, R] := APkt.Timestamp;
  strgMain.Cells[COL_DIR,  R] := APkt.Direction;
  strgMain.Cells[COL_ADDR, R] := Format('0x%.2X', [APkt.Address]);
  strgMain.Cells[COL_FUNC, R] := Format('0x%.2X', [APkt.FunctionCode]);
  strgMain.Cells[COL_LEN,  R] := IntToStr(APkt.Length);
  if APkt.ValidCRC then
    strgMain.Cells[COL_CRC, R] := 'OK'
  else
    strgMain.Cells[COL_CRC, R] := 'BAD';
  strgMain.Cells[COL_HEX,  R] := APkt.HexString;
  strgMain.Cells[COL_DESC, R] := APkt.Description;
  { Store packet pointer for O(1) DrawCell colour lookup }
  strgMain.Objects[COL_NUM, R] := APkt;
end;

procedure TfrmMain.RebuildGrid;
{ Rewrites the entire grid from FPackets or FFiltered.
  Called when:
    (a) edtFilter changes — display source has changed
    (b) The 10 000-packet cap rolls over — all row numbers shift

  Optimisation: RowCount is set once to 1 + Src.Count (pre-sizing the
  row array), then cells are written by direct index [col, I+1] inside a
  BeginUpdate/EndUpdate block.  This is O(n) with minimal heap churn. }
var
  I:    Integer;
  APkt: TModbusPacket;
  Src:  TList;
begin
  if FFilterActive then Src := FFiltered else Src := FPackets;

  strgMain.BeginUpdate;
  try
    strgMain.RowCount := 1;               { back to header-only }
    strgMain.RowCount := 1 + Src.Count;   { pre-allocate all rows at once }
    for I := 0 to Src.Count - 1 do
    begin
      APkt := TModbusPacket(Src[I]);
      strgMain.Cells[COL_NUM,  I+1] := IntToStr(FPackets.IndexOf(APkt) + 1);
      strgMain.Cells[COL_TIME, I+1] := APkt.Timestamp;
      strgMain.Cells[COL_DIR,  I+1] := APkt.Direction;
      strgMain.Cells[COL_ADDR, I+1] := Format('0x%.2X', [APkt.Address]);
      strgMain.Cells[COL_FUNC, I+1] := Format('0x%.2X', [APkt.FunctionCode]);
      strgMain.Cells[COL_LEN,  I+1] := IntToStr(APkt.Length);
      if APkt.ValidCRC then
        strgMain.Cells[COL_CRC, I+1] := 'OK'
      else
        strgMain.Cells[COL_CRC, I+1] := 'BAD';
      strgMain.Cells[COL_HEX,  I+1] := APkt.HexString;
      strgMain.Cells[COL_DESC, I+1] := APkt.Description;
      strgMain.Objects[COL_NUM, I+1] := APkt;
    end;
  finally
    strgMain.EndUpdate;
  end;

  FPendingRows := 0;   { all rows now in grid; nothing pending }

  if chkbAutoScroll.Checked and (strgMain.RowCount > 1) then
    strgMain.Row := strgMain.RowCount - 1;
end;

{ =============================================================================
  Filter
  ============================================================================= }

procedure TfrmMain.edtFilterChange(Sender: TObject);
{ Fired on every keystroke in edtFilter.
  Resets FPendingRows (pending rows from the old display state are discarded —
  RebuildGrid will write all matching rows from scratch) then calls
  ApplyFilter + RebuildGrid for an immediate full repaint.
  This is intentionally O(n) on packet count; at 10 000 packets it is fast
  enough that no debounce is needed. }
begin
  FFilterText   := Trim(edtFilter.Text);
  FFilterActive := FFilterText <> '';
  FPendingRows  := 0;
  ApplyFilter;
  RebuildGrid;
end;

procedure TfrmMain.sbtnClearFilterClick(Sender: TObject);
{ Setting the text to '' fires edtFilterChange which removes the filter
  and shows all packets. }
begin
  edtFilter.Text := '';
end;

procedure TfrmMain.ApplyFilter;
{ Rebuilds FFiltered by scanning FPackets.
  Called by edtFilterChange; NOT called inside OnPacketReady (incoming packets
  are matched inline there to avoid iterating the entire list on every packet). }
var
  I:     Integer;
  Lower: string;
begin
  FFiltered.Clear;
  if not FFilterActive then Exit;
  Lower := LowerCase(FFilterText);
  for I := 0 to FPackets.Count - 1 do
    if PacketMatchesFilter(TModbusPacket(FPackets[I]), Lower) then
      FFiltered.Add(FPackets[I]);
end;

function TfrmMain.PacketMatchesFilter(APkt: TModbusPacket;
                                       const ALower: string): Boolean;
{ Multi-field substring search.  ALower is already lowercased by the caller
  to avoid repeated conversions when called from ApplyFilter (n iterations).
  Returns True on the first match to minimise CPU time per packet. }
var
  HexNS, PktHexNS: string;
begin
  Result := False;
  if APkt = nil then Exit;

  { 1. Hex string match (with spaces, e.g. "01 03 00") }
  if Pos(ALower, LowerCase(APkt.HexString))   > 0 then begin Result:=True; Exit; end;
  { 2. Slave address (decimal, e.g. "17") }
  if Pos(ALower, IntToStr(APkt.Address))       > 0 then begin Result:=True; Exit; end;
  { 3. Function code (decimal) }
  if Pos(ALower, IntToStr(APkt.FunctionCode))  > 0 then begin Result:=True; Exit; end;
  { 4. Function code (hex, e.g. "03") }
  if Pos(ALower, LowerCase(Format('%0.x', [APkt.FunctionCode]))) > 0
    then begin Result:=True; Exit; end;
  { 5. Direction ("tx" or "rx") }
  if Pos(ALower, LowerCase(APkt.Direction))    > 0 then begin Result:=True; Exit; end;
  { 6. Description text }
  if Pos(ALower, LowerCase(APkt.Description))  > 0 then begin Result:=True; Exit; end;
  { 7. Timestamp }
  if Pos(ALower, LowerCase(APkt.Timestamp))    > 0 then begin Result:=True; Exit; end;
  { 8. Hex without spaces (e.g. "0103" matches "01 03 …") }
  HexNS    := StringReplace(ALower, ' ', '', [rfReplaceAll]);
  PktHexNS := LowerCase(StringReplace(APkt.HexString, ' ', '', [rfReplaceAll]));
  if Pos(HexNS, PktHexNS)                      > 0 then begin Result:=True; Exit; end;

  { 9. Special direction keywords }
  if (ALower='tx') or (ALower='transmit') or (ALower='send') then
    begin Result := APkt.Direction = 'TX'; Exit; end;
  if (ALower='rx') or (ALower='receive')  or (ALower='recv') then
    begin Result := APkt.Direction = 'RX'; Exit; end;
  { 10. Error/exception keywords }
  if (ALower='error') or (ALower='exception') or (ALower='invalid') then
    begin Result := APkt.IsException or not APkt.ValidCRC; Exit; end;
  { 11. Function-group keywords }
  if ALower = 'read'  then begin Result := APkt.FunctionCode in [$01,$02,$03,$04]; Exit; end;
  if ALower = 'write' then begin Result := APkt.FunctionCode in [$05,$06,$0F,$10]; Exit; end;
end;

{ =============================================================================
  Clear
  ============================================================================= }

procedure TfrmMain.btnClearClick(Sender: TObject);
{ Resets the application to a post-start "empty" state without stopping capture.
  Order matters: grid is cleared before FPackets so no dangling Object pointers
  exist during the EndUpdate repaint. }
var
  I: Integer;
begin
  { Reset grid to header-only row }
  strgMain.BeginUpdate;
  try
    strgMain.RowCount := 1;
  finally
    strgMain.EndUpdate;
  end;

  { Release packet memory }
  FFiltered.Clear;
  for I := 0 to FPackets.Count - 1 do
    TModbusPacket(FPackets[I]).Free;
  FPackets.Clear;

  { Reset all counters }
  FPacketCount  := 0;
  FErrorCount   := 0;
  FLastCount    := 0;
  FPendingRows  := 0;
  FLastStatTime := Now;

  { Reset filter state }
  FFilterActive  := False;
  FFilterText    := '';
  edtFilter.Text := '';

  ClearDetails;
  UpdateStats;

  if FRunning then
    pnlBottomStatusBar.Caption :=
      Format('Monitoring %s @ %d baud — log cleared',
        [LazSerial1.Device, ConstsBaud[LazSerial1.BaudRate]])
  else
    pnlBottomStatusBar.Caption := 'Log cleared';
end;

procedure TfrmMain.chkbShowHexChange(Sender: TObject);
{ Toggles the Hex column visibility by setting its width to 0 (hidden) or 180.
  TStringGrid does not have a column Visible property; zero-width is the
  standard LCL idiom for hiding a column. }
begin
  if chkbShowHex.Checked then
    strgMain.ColWidths[COL_HEX] := 180
  else
    strgMain.ColWidths[COL_HEX] := 0;
end;

{ =============================================================================
  Packet detail panel
  ============================================================================= }

procedure TfrmMain.ClearDetails;
{ Removes any dynamic controls from grpPacketDetails (the TMemo created by
  ShowPacketDetails) and replaces them with a placeholder label.
  Called at startup and by btnClearClick. }
begin
  while grpPacketDetails.ControlCount > 0 do
    grpPacketDetails.Controls[0].Free;
  with TLabel.Create(grpPacketDetails) do
  begin
    Parent     := grpPacketDetails;
    Caption    := 'Select a packet to view details';
    Font.Color := $00888888;
    Left       := 8;
    Top        := 20;
  end;
end;

procedure TfrmMain.ShowPacketDetails(APkt: TModbusPacket);
{ Displays a full breakdown of APkt in grpPacketDetails.
  A new TMemo is created on every call (rather than keeping one persistent
  memo and clearing it) to avoid flickering on rapid row selections.

  Sections displayed:
    • Header fields: Timestamp, Direction, Length, Address, Function, Exception, CRC
    • Full Hex: space-separated byte string
    • Raw Bytes: 16 bytes per line with two-space indent
    • Data Bytes: payload only (address, function, CRC excluded), 16/line
    • Description: parsed text from UModbusParser }
var
  Memo: TMemo;
  I:    Integer;
  Line: string;
begin
  if APkt = nil then begin ClearDetails; Exit; end;

  { Remove previous controls (placeholder label or old memo) }
  while grpPacketDetails.ControlCount > 0 do
    grpPacketDetails.Controls[0].Free;

  Memo            := TMemo.Create(grpPacketDetails);
  Memo.Parent     := grpPacketDetails;
  Memo.Align      := alClient;     { fills the group box }
  Memo.ReadOnly   := True;
  Memo.ScrollBars := ssVertical;
  Memo.WordWrap   := False;        { hex lines must not wrap }
  Memo.Font.Name  := 'Consolas';
  Memo.Font.Size  := 9;
  Memo.Color      := $001E1E1E;    { match main grid background }
  Memo.Font.Color := $00CCCCCC;

  Memo.Lines.BeginUpdate;
  try
    { ── Header fields ── }
    Memo.Lines.Add(Format('Timestamp     : %s',  [APkt.Timestamp]));
    Memo.Lines.Add(Format('Direction     : %s',  [APkt.Direction]));
    Memo.Lines.Add(Format('Length        : %d bytes', [APkt.Length]));
    Memo.Lines.Add(Format('Device Address: %d  (0x%.2X)',
                          [APkt.Address, APkt.Address]));
    Memo.Lines.Add(Format('Function Code : 0x%.2X', [APkt.FunctionCode]));
    Memo.Lines.Add(Format('          (%s)', [GetFunctionName(APkt.FunctionCode)]));

    if APkt.IsException then
      Memo.Lines.Add(Format('Exception     : 0x%.2X  (%s)',
        [APkt.ExceptionCode, GetExceptionName(APkt.ExceptionCode)]));

    if APkt.ValidCRC then
      Memo.Lines.Add(Format('CRC           : 0x%.4X  (Valid)',   [APkt.CRC]))
    else
      Memo.Lines.Add(Format('CRC           : 0x%.4X  (INVALID)', [APkt.CRC]));

    { ── Hex dump ── }
    Memo.Lines.Add('');
    Memo.Lines.Add('Full Hex:');
    Memo.Lines.Add('  ' + APkt.HexString);

    { ── Raw bytes, 16 per line ── }
    Memo.Lines.Add('');
    Memo.Lines.Add('Raw Bytes:');
    Line := '  ';
    for I := 0 to High(APkt.Raw) do
    begin
      if (I > 0) and (I mod 16 = 0) then
      begin
        Memo.Lines.Add(Line);
        Line := '  ';
      end;
      Line := Line + Format('%02X ', [APkt.Raw[I]]);
    end;
    if Line <> '  ' then Memo.Lines.Add(Line);

    { ── Data payload bytes, 16 per line (omitted if empty) ── }
    if Length(APkt.Data) > 0 then
    begin
      Memo.Lines.Add('');
      Memo.Lines.Add(Format('Data Bytes (%d):', [Length(APkt.Data)]));
      Line := '  ';
      for I := 0 to High(APkt.Data) do
      begin
        if (I > 0) and (I mod 16 = 0) then
        begin
          Memo.Lines.Add(Line);
          Line := '  ';
        end;
        Line := Line + Format('%.2X ', [APkt.Data[I]]);
      end;
      if Line <> '  ' then Memo.Lines.Add(Line);
    end;

    { ── Parsed description ── }
    Memo.Lines.Add('');
    Memo.Lines.Add('Description:');
    Memo.Lines.Add('  ' + APkt.Description);
  finally
    Memo.Lines.EndUpdate;
  end;
end;

{ =============================================================================
  Stats and batched grid flush
  ============================================================================= }

procedure TfrmMain.UpdateStats;
{ Called every second by TimerStatsTimer.  Combines two duties to minimise
  timer overhead:

  PART 1 — GRID FLUSH
  If FPendingRows > 0, all pending packets (the tail of FPackets or FFiltered)
  are appended to strgMain in a single BeginUpdate/EndUpdate block:
    • RowCount is set once to StartRow + FPendingRows.
    • Cells are written by pre-computed row index (no RowCount changes in loop).
    • Objects[COL_NUM] is set for O(1) colour lookup in DrawCell.
  After flushing, FPendingRows is reset and the grid is scrolled if needed.

  PART 2 — STATS LABEL
  Once per second: recalculates the packet rate and updates pnlStatusBar. }
var
  Elapsed:          Double;
  Rate:             Double;
  Disp:             Integer;
  Src:              TList;
  StartRow, I:      Integer;
  APkt:             TModbusPacket;
begin
  { ── Part 1: flush pending rows ── }
  if FPendingRows > 0 then
  begin
    if FFilterActive then Src := FFiltered else Src := FPackets;
    StartRow := strgMain.RowCount;   { index of the first new row }

    strgMain.BeginUpdate;
    try
      { Extend row array once }
      strgMain.RowCount := StartRow + FPendingRows;
      { Fill all new rows by index — no RowCount changes inside this loop }
      for I := 0 to FPendingRows - 1 do
      begin
        APkt := TModbusPacket(Src[Src.Count - FPendingRows + I]);
        strgMain.Cells[COL_NUM,  StartRow+I] := IntToStr(FPackets.IndexOf(APkt)+1);
        strgMain.Cells[COL_TIME, StartRow+I] := APkt.Timestamp;
        strgMain.Cells[COL_DIR,  StartRow+I] := APkt.Direction;
        strgMain.Cells[COL_ADDR, StartRow+I] := Format('0x%.2X', [APkt.Address]);
        strgMain.Cells[COL_FUNC, StartRow+I] := Format('0x%.2X', [APkt.FunctionCode]);
        strgMain.Cells[COL_LEN,  StartRow+I] := IntToStr(APkt.Length);
        if APkt.ValidCRC then
          strgMain.Cells[COL_CRC, StartRow+I] := 'OK'
        else
          strgMain.Cells[COL_CRC, StartRow+I] := 'BAD';
        strgMain.Cells[COL_HEX,  StartRow+I] := APkt.HexString;
        strgMain.Cells[COL_DESC, StartRow+I] := APkt.Description;
        strgMain.Objects[COL_NUM, StartRow+I] := APkt;
      end;
    finally
      strgMain.EndUpdate;
    end;

    FPendingRows := 0;

    if chkbAutoScroll.Checked then
      strgMain.Row := strgMain.RowCount - 1;
  end;

  { ── Part 2: stats label (once per second) ── }
  Elapsed := MilliSecondsBetween(Now, FLastStatTime) / 1000.0;
  if Elapsed < 1.0 then Exit;

  Rate := (FPacketCount - FLastCount) / Elapsed;
  if FFilterActive then Disp := FFiltered.Count else Disp := FPackets.Count;

  pnlStatusBar.Caption :=
    Format('Packets: %d  |  Errors: %d  |  Rate: %.1f/s  |  Displaying: %d',
      [FPacketCount, FErrorCount, Rate, Disp]);

  FLastCount    := FPacketCount;
  FLastStatTime := Now;
end;

procedure TfrmMain.TimerStatsTimer(Sender: TObject);
{ 1-second timer tick.  Delegates entirely to UpdateStats. }
begin
  UpdateStats;
end;

{ =============================================================================
  Export to CSV
  ============================================================================= }

function TfrmMain.BuildCSVLine(APkt: TModbusPacket): string;
{ Formats one RFC-4180 CSV record.  All string fields are double-quoted.
  Embedded double-quotes in Description are replaced with single quotes.
  CR and LF in Description are stripped/replaced to keep records single-line.
  Column order matches the grid: Timestamp, Direction, Address (decimal),
  Function (hex), Length, CRC Valid (true/false), Hex Data, Description. }
var
  Desc: string;
begin
  Desc := StringReplace(APkt.Description, '"',  '''', [rfReplaceAll]);
  Desc := StringReplace(Desc,             #13,  '',   [rfReplaceAll]);
  Desc := StringReplace(Desc,             #10,  ' ',  [rfReplaceAll]);
  if APkt.ValidCRC then
    Result := Format('"%s","%s",%d,0x%.2X,%d,true,"%s","%s"' + LineEnding,
      [APkt.Timestamp, APkt.Direction, APkt.Address, APkt.FunctionCode,
       APkt.Length, APkt.HexString, Desc])
  else
    Result := Format('"%s","%s",%d,0x%.2X,%d,false,"%s","%s"' + LineEnding,
      [APkt.Timestamp, APkt.Direction, APkt.Address, APkt.FunctionCode,
       APkt.Length, APkt.HexString, Desc]);
end;

procedure TfrmMain.btnExportClick(Sender: TObject);
{ Exports either the filtered subset or all packets to a CSV file.
  File name defaults to modbus_log_YYYYMMDD_HHMMSS.csv.
  Uses Pascal file I/O (AssignFile/Rewrite/WriteLn/CloseFile) — no stream
  objects needed for a simple sequential write. }
var
  Dlg: TSaveDialog;
  F:   TextFile;
  I:   Integer;
  Src: TList;
begin
  if FPackets.Count = 0 then
  begin
    ShowMessage('No packets to export.');
    Exit;
  end;

  Dlg := TSaveDialog.Create(nil);
  try
    Dlg.Title      := 'Export Modbus Log';
    Dlg.Filter     := 'CSV files (*.csv)|*.csv|All files (*.*)|*.*';
    Dlg.DefaultExt := 'csv';
    Dlg.FileName   := Format('modbus_log_%s.csv',
                        [FormatDateTime('yyyymmdd_hhnnss', Now)]);
    if not Dlg.Execute then Exit;

    if FFilterActive then Src := FFiltered else Src := FPackets;

    AssignFile(F, Dlg.FileName);
    Rewrite(F);
    try
      WriteLn(F,
        'Timestamp,Direction,Address,Function,Length,CRC Valid,Hex Data,Description');
      for I := 0 to Src.Count - 1 do
        Write(F, BuildCSVLine(TModbusPacket(Src[I])));
    finally
      CloseFile(F);
    end;

    ShowMessage(Format('Exported %d packets to:'#13#10'%s',
      [Src.Count, Dlg.FileName]));
  finally
    Dlg.Free;
  end;
end;

{ =============================================================================
  UI state helpers
  ============================================================================= }

procedure TfrmMain.SetControlsRunning(AOn: Boolean);
{ Maintains a consistent button state: while capturing, Start and Comm Config
  are disabled (port is in use); Stop is enabled.  Vice versa when idle. }
begin
  btnStart.Enabled      := not AOn;
  btnStop.Enabled       := AOn;
  btnCommConfig.Enabled := not AOn;
end;

end.

