unit UModbusUtils;

{$mode objfpc}{$H+}

{ =============================================================================
  UModbusUtils — Modbus RTU low-level utility functions
  =============================================================================

  DISCLAIMER: All documentation was generated by Antropic's Claude Sonnet 4.6

  PURPOSE
  ───────
  Provides the mathematical and formatting primitives that the rest of the
  sniffer depends on.  Every function here is stateless (no global variables,
  no side effects) so each can be tested in isolation.

  CONTENTS
  ────────
    CRC16            — compute the Modbus RTU CRC-16 checksum
    IsValidCRC       — validate the CRC stored at the end of a frame
    BytesToHex       — format a byte array as a readable hex string
    ParseExceptionCode — thin wrapper for GetExceptionName (UModbusTypes)
    BigEndianWord    — read a 16-bit big-endian value from a byte array
    LittleEndianWord — read a 16-bit little-endian value from a byte array
    FormatTimestamp  — format a TDateTime as "HH:MM:SS.mmm"

  DEPENDENCIES
  ────────────
  UModbusTypes — for TByteArray and GetExceptionName.
  No LCL units; this unit is UI-independent and could be reused in a
  non-graphical Modbus tool without modification.

  CRC-16 ALGORITHM BACKGROUND
  ────────────────────────────
  Modbus RTU uses a 16-bit CRC with the following parameters
  (as defined in the Modbus Serial Line Protocol and Implementation Guide V1.02):

    Width:        16 bits
    Polynomial:   0x8005 (in normal representation)
                  0xA001 (reflected / bit-reversed, used in the LSB-first loop)
    Initial value:0xFFFF
    Input/output: reflected (bit-by-bit, implicit in the LSB-first loop)
    Final XOR:    0x0000 (no final inversion)

  The "reflected" polynomial 0xA001 is equivalent to processing each byte
  LSB-first rather than MSB-first, which matches the Modbus specification's
  description of the algorithm.

  BYTE ORDER IN MODBUS RTU
  ────────────────────────
  Modbus RTU uses big-endian (network byte order) for all 16-bit data values
  within the payload (register addresses, quantities, register values).
  The CRC-16 at the end of every frame is the only exception: it is stored
  little-endian (low byte first, high byte second).

  This is why the unit provides both BigEndianWord (for payload parsing) and
  LittleEndianWord (for CRC extraction).

  ============================================================================= }

interface

uses
  Classes,       { TObject — not directly used but standard practice }
  SysUtils,      { Format, DecodeTime }
  UModbusTypes;  { TByteArray, GetExceptionName }

{ -----------------------------------------------------------------------------
  CRC16
  -----------------------------------------------------------------------------
  Computes the Modbus RTU CRC-16 over ALength bytes of AData.

  Parameters:
    AData   — source byte array; must have at least ALength elements
    ALength — number of bytes to include in the calculation

  Returns:
    The 16-bit CRC as a Word (little-endian value, not yet split into bytes).

  Usage:
    To verify a received frame, pass Len-2 as ALength (exclude the two CRC
    bytes) and compare the result to the CRC stored in the frame.
    To generate a CRC for a frame being built, pass the full data length.

  Algorithm (LSB-first, reflected polynomial):
    1. Initialise the CRC register to 0xFFFF.
    2. For each byte:
         a. XOR the byte into the low byte of the CRC register.
         b. For each of the 8 bits:
              if the LSB of CRC is 1: CRC = (CRC shr 1) XOR 0xA001
              else:                   CRC =  CRC shr 1
    3. The 16-bit result is the CRC. }
function CRC16(const AData: TByteArray; ALength: Integer): Word;

{ -----------------------------------------------------------------------------
  IsValidCRC
  -----------------------------------------------------------------------------
  Validates the CRC-16 appended to a complete Modbus RTU frame.

  Parameters:
    AData — the complete frame including the two CRC bytes at the end

  Returns:
    True  — CRC computed over AData[0..Len-3] matches the stored CRC
    False — frame too short (< 4 bytes) or CRC mismatch

  CRC storage format in the frame:
    AData[Len-2] = low byte of CRC  (first on wire)
    AData[Len-1] = high byte of CRC (second on wire)

  Minimum valid Modbus RTU frame: 4 bytes (Addr + Func + CRC_Lo + CRC_Hi).
  Frames shorter than 4 bytes are rejected unconditionally. }
function IsValidCRC(const AData: TByteArray): Boolean;

{ -----------------------------------------------------------------------------
  BytesToHex
  -----------------------------------------------------------------------------
  Converts a byte array to an uppercase, space-separated hex string.

  Parameters:
    AData — array of bytes to format

  Returns:
    A string like "01 03 00 00 00 02 C4 0B"
    Empty string ("") if AData has zero elements.

  Format notes:
    • Each byte is formatted as exactly two uppercase hex digits (e.g. "0A").
    • Bytes are separated by a single space.
    • No leading or trailing spaces.

  This format is used for:
    • The HexString field of TModbusPacket (displayed in COL_HEX)
    • The "Full Hex" section of the detail panel
    • Filter matching in UMain.PacketMatchesFilter }
function BytesToHex(const AData: TByteArray): string;

{ -----------------------------------------------------------------------------
  ParseExceptionCode
  -----------------------------------------------------------------------------
  Returns the human-readable name of a Modbus exception code.
  Thin convenience wrapper around GetExceptionName (UModbusTypes).

  Parameters:
    ACode — the exception code byte from Raw[2] of an exception response

  Returns:
    e.g. "Illegal Data Address" for code 0x02
         "Unknown Exception (0x0C)" for an unrecognised code

  Note: this function exists so callers that only use UModbusUtils do not
  need to add a separate dependency on UModbusTypes. }
function ParseExceptionCode(ACode: Byte): string;

{ -----------------------------------------------------------------------------
  BigEndianWord
  -----------------------------------------------------------------------------
  Reads a 16-bit unsigned integer from two consecutive bytes stored in
  big-endian (Motorola / network) byte order.

  Parameters:
    AData   — source byte array
    AOffset — index of the high byte; the low byte is at AOffset + 1

  Returns:
    (AData[AOffset] SHL 8) OR AData[AOffset + 1]

  Modbus RTU uses big-endian for all payload 16-bit values:
    • Register start addresses in TX frames
    • Register quantities in TX frames
    • Register values in RX frames
    • Coil output values (0xFF00 = ON, 0x0000 = OFF)

  Caller responsibility: ensure AOffset + 1 < Length(AData) before calling
  to avoid an out-of-range runtime error. }
function BigEndianWord(const AData: TByteArray; AOffset: Integer): Word;

{ -----------------------------------------------------------------------------
  LittleEndianWord
  -----------------------------------------------------------------------------
  Reads a 16-bit unsigned integer from two consecutive bytes stored in
  little-endian (Intel) byte order.

  Parameters:
    AData   — source byte array
    AOffset — index of the low byte; the high byte is at AOffset + 1

  Returns:
    AData[AOffset] OR (AData[AOffset + 1] SHL 8)

  Modbus RTU uses little-endian only for the CRC-16 stored at the end of
  every frame.  All other 16-bit quantities use BigEndianWord.

  Caller responsibility: ensure AOffset + 1 < Length(AData) before calling. }
function LittleEndianWord(const AData: TByteArray; AOffset: Integer): Word;

{ -----------------------------------------------------------------------------
  FormatTimestamp
  -----------------------------------------------------------------------------
  Formats a TDateTime value as a fixed-width time string "HH:MM:SS.mmm".

  Parameters:
    ANow — the datetime to format (typically obtained from Now at parse time)

  Returns:
    A 12-character string, e.g. "14:35:07.042"

  The date component of ANow is ignored — only the time portion is extracted
  via DecodeTime.  This is intentional: packet timestamps show only the time
  of day because Modbus sniffers are typically used for short diagnostic
  sessions where the date is irrelevant.

  The millisecond component provides 1 ms resolution, matching LazSerial's
  Synchronize granularity and sufficient for Modbus timing analysis at all
  standard baud rates. }
function FormatTimestamp(ANow: TDateTime): string;

implementation

{ =============================================================================
  CRC16
  ============================================================================= }

function CRC16(const AData: TByteArray; ALength: Integer): Word;
{ LSB-first CRC-16 with reflected polynomial 0xA001.
  The inner loop processes each bit of each byte from LSB to MSB,
  which is equivalent to reflecting both the input data and the polynomial.

  Performance note: this is a bit-by-bit implementation (8 iterations per
  byte).  For very high baud rates a table-driven implementation would be
  faster, but at the packet rates seen in Modbus RTU (typically < 1000
  frames/s) this is negligible. }
var
  I, J: Integer;
  B:    Byte;
begin
  Result := $FFFF;                    { initialise CRC register }
  for I := 0 to ALength - 1 do
  begin
    B      := AData[I];
    Result := Result xor B;           { XOR byte into low byte of CRC }
    for J := 0 to 7 do               { process each bit LSB-first }
    begin
      if (Result and $0001) <> 0 then
        Result := (Result shr 1) xor $A001  { LSB was 1: shift and XOR polynomial }
      else
        Result := Result shr 1;             { LSB was 0: shift only }
    end;
  end;
  { Result now contains the 16-bit CRC.  To append to a frame:
      frame[Len]   := Lo(Result)   { low byte first  }
      frame[Len+1] := Hi(Result)   { high byte second }  }
end;

{ =============================================================================
  IsValidCRC
  ============================================================================= }

function IsValidCRC(const AData: TByteArray): Boolean;
{ Extracts the two CRC bytes from the tail of AData and compares them to the
  CRC computed over the preceding bytes.

  Frame layout:
    AData[0]       = Slave Address
    AData[1]       = Function Code
    AData[2..Len-3] = Data payload (may be empty)
    AData[Len-2]   = CRC low byte  ← little-endian
    AData[Len-1]   = CRC high byte ← little-endian

  The stored CRC is reconstructed as:
    PacketCRC := Lo_byte OR (Hi_byte SHL 8)
  which is the inverse of the split performed during frame construction. }
var
  Calculated, PacketCRC: Word;
  Len: Integer;
begin
  Len := Length(AData);
  if Len < 4 then          { minimum: Addr(1) + Func(1) + CRC(2) = 4 bytes }
  begin
    Result := False;
    Exit;
  end;
  Calculated := CRC16(AData, Len - 2);        { compute over everything except CRC bytes }
  PacketCRC  := Word(AData[Len - 2])           { low byte }
             or (Word(AData[Len - 1]) shl 8);  { high byte }
  Result := (Calculated = PacketCRC);
end;

{ =============================================================================
  BytesToHex
  ============================================================================= }

function BytesToHex(const AData: TByteArray): string;
{ Plain string concatenation is used instead of TStringBuilder to avoid
  FPC's overload ambiguity between Append(string) and Append(AnsiChar),
  which caused single-character results to be truncated in some FPC versions.

  Format('%.2X', [B]) always produces exactly 2 uppercase hex digits:
    0x00 → "00",  0x0A → "0A",  0xFF → "FF" }
var
  I: Integer;
begin
  Result := '';
  for I := 0 to High(AData) do
  begin
    if I > 0 then Result := Result + ' ';
    Result := Result + Format('%.2X', [AData[I]]);
  end;
end;

{ =============================================================================
  ParseExceptionCode
  ============================================================================= }

function ParseExceptionCode(ACode: Byte): string;
{ Delegates to GetExceptionName (UModbusTypes) which owns the exception code
  table.  This wrapper keeps the interface of UModbusUtils self-contained:
  callers that only depend on UModbusUtils do not need to know about
  UModbusTypes.GetExceptionName directly. }
begin
  Result := GetExceptionName(ACode);
end;

{ =============================================================================
  BigEndianWord
  ============================================================================= }

function BigEndianWord(const AData: TByteArray; AOffset: Integer): Word;
{ High byte is at AOffset, low byte is at AOffset + 1.
  This matches the Modbus specification's "most significant byte first" ordering
  for all payload integers.

  Example — register address 0x006E stored at offset 2:
    AData[2] = 0x00  (high byte)
    AData[3] = 0x6E  (low byte)
    BigEndianWord(AData, 2) = (0x00 SHL 8) OR 0x6E = 0x006E = 110 }
begin
  Result := (Word(AData[AOffset]) shl 8) or Word(AData[AOffset + 1]);
end;

{ =============================================================================
  LittleEndianWord
  ============================================================================= }

function LittleEndianWord(const AData: TByteArray; AOffset: Integer): Word;
{ Low byte is at AOffset, high byte is at AOffset + 1.
  Used exclusively for reading the CRC-16 from the tail of a frame.

  Example — CRC 0xC40B stored at the last two bytes:
    AData[Len-2] = 0x0B  (low byte, transmitted first)
    AData[Len-1] = 0xC4  (high byte, transmitted second)
    LittleEndianWord(AData, Len-2) = 0x0B OR (0xC4 SHL 8) = 0xC40B }
begin
  Result := Word(AData[AOffset]) or (Word(AData[AOffset + 1]) shl 8);
end;

{ =============================================================================
  FormatTimestamp
  ============================================================================= }

function FormatTimestamp(ANow: TDateTime): string;
{ DecodeTime splits the fractional day portion of ANow into hours, minutes,
  seconds, and milliseconds.  The date portion is silently discarded.

  Output format: "HH:MM:SS.mmm"
    HH  = 00–23 (always two digits)
    MM  = 00–59 (always two digits)
    SS  = 00–59 (always two digits)
    mmm = 000–999 (always three digits)

  The fixed width ensures that all timestamps in the grid column align
  correctly with the Consolas monospace font used by strgMain. }
var
  H, M, S, MS: Word;
begin
  DecodeTime(ANow, H, M, S, MS);
  Result := Format('%02d:%02d:%02d.%03d', [H, M, S, MS]);
end;

end.

