unit UModbusParser;

{$mode objfpc}{$H+}

{ =============================================================================
  UModbusParser — Modbus RTU frame parser and description builder
  =============================================================================

  DISCLAIMER: All documentation was generated by Antropic's Claude Sonnet 4.6

  PURPOSE
  ───────
  Transforms a raw byte array (a complete Modbus RTU frame) into a fully
  populated TModbusPacket, including:
    • Protocol field extraction (address, function code, exception, CRC)
    • Payload slicing (the Data field, between func byte and CRC)
    • CRC-16 validation
    • Human-readable description string generation

  This unit contains the only Modbus protocol knowledge in the application.
  UModbusSniffer handles byte accumulation and frame boundary detection;
  UModbusParser handles what the bytes mean.

  PUBLIC API
  ──────────
  Only ParsePacket is exported.  The three description-builder helpers
  (GenerateRequestDescription, GenerateResponseDescription,
  GenerateDescription) are private to the implementation section.

  DESCRIPTION FORMAT
  ──────────────────
  The Description field of TModbusPacket uses a pipe-delimited format so
  each component is visually distinct in the narrow grid column:

    "Addr: 0x01 | Read Holding Registers | Start: 0x0000, Qty: 10"
    "Addr: 0x01 | Read Holding Registers | Bytes: 20 | Values: 100 200 …"
    "Addr: 0x03 | Exception: 0x02 (Illegal Data Address)"

  For TX frames (master requests) the description shows what the master is
  asking for (start address, quantity, values to write).
  For RX frames (slave responses) the description shows what the slave
  returned (byte count, decoded register or coil values).

  DISPLAY LIMITS
  ──────────────
  To keep the description readable in the grid column, value lists are
  truncated:
    • Coil bytes:     up to 20 bytes shown, then "..."
    • Register values: up to 20 registers for most functions
    • FC 23 response:  up to 4 registers (response half only)
  All values beyond the limit still exist in TModbusPacket.Data and are
  visible in the detail panel's full hex dump.

  FRAME LAYOUT REMINDER (see also UModbusTypes)
  ─────────────────────────────────────────────
    AData[0]         = Slave Address  → Pkt.Address
    AData[1]         = Function Code  → Pkt.FunctionCode  (bit 7 = exception)
    AData[2..Len-3]  = Data payload   → Pkt.Data
    AData[Len-2]     = CRC low byte   ┐ little-endian
    AData[Len-1]     = CRC high byte  ┘ → Pkt.CRC

  DEPENDENCIES
  ────────────
  SysUtils      — Format, IntToStr, Now, Move
  UModbusTypes  — TModbusPacket, TByteArray, FUNC_* constants,
                  GetFunctionName, GetExceptionName
  UModbusUtils  — BigEndianWord, LittleEndianWord, CRC16,
                  BytesToHex, FormatTimestamp

  ============================================================================= }

interface

uses
  SysUtils,      { Format, IntToStr, Now, Move }
  UModbusTypes,  { TModbusPacket, TByteArray, FUNC_* constants }
  UModbusUtils;  { BigEndianWord, LittleEndianWord, CRC16, BytesToHex, FormatTimestamp }

{ -----------------------------------------------------------------------------
  ParsePacket
  -----------------------------------------------------------------------------
  Parses a complete Modbus RTU frame into a TModbusPacket.

  Parameters:
    AData      — the raw frame bytes including address, function, payload,
                 and the two CRC bytes at the end.  Must not be empty.
    ADirection — 'TX' for a master request, 'RX' for a slave response.
                 Controls which description builder is called and affects
                 how ambiguous frames are interpreted.

  Returns:
    A newly allocated TModbusPacket.  The caller owns this object and must
    free it when done.  The function never returns nil — even a malformed
    frame produces a packet with a descriptive error in the Description field.

  Behaviour for short frames (< 4 bytes):
    All fields that can be populated are populated (Raw, HexString, Length,
    Timestamp, Direction).  Description is set to an error message.
    CRC validation is skipped.  The packet is returned immediately.

  Behaviour for frames with a bad CRC:
    All fields are populated normally.  ValidCRC = False.
    The frame is not discarded — corrupt frames are still useful for
    diagnosing noise, baud rate mismatches, or framing errors. }
function ParsePacket(const AData: TByteArray; const ADirection: string): TModbusPacket;

implementation

{ =============================================================================
  GenerateRequestDescription  (private)
  =============================================================================
  Builds the payload portion of the Description string for TX (master request)
  frames.  Returns '' for unknown or unsupported function codes, and also for
  frames whose Data field is shorter than the minimum for that function.

  The result is appended to the function-name prefix by GenerateDescription:
    "… | Read Holding Registers | Start: 0x0000, Qty: 10"
                                  ^^^^^^^^^^^^^^^^^^^^^^^^
                                  returned by this function

  Data field layout per function code (all addresses and quantities are
  big-endian 16-bit values extracted with BigEndianWord):

    FC 01/02/03/04 (Read):
      Data[0..1] = Start address
      Data[2..3] = Quantity of coils/registers to read

    FC 05 (Write Single Coil):
      Data[0..1] = Output address
      Data[2..3] = Output value (0xFF00 = ON, 0x0000 = OFF, other = raw hex)

    FC 06 (Write Single Register):
      Data[0..1] = Register address
      Data[2..3] = Register value (displayed as decimal)

    FC 15/0F (Write Multiple Coils):
      Data[0..1] = Start address
      Data[2..3] = Quantity of coils
      Data[4]    = Byte count (n)
      Data[5..4+n] = Coil values packed LSB-first, 1 bit per coil

    FC 16/10 (Write Multiple Registers):
      Data[0..1] = Start address
      Data[2..3] = Quantity of registers
      Data[4]    = Byte count (n = quantity × 2)
      Data[5..4+n] = Register values as big-endian 16-bit pairs

    FC 23/17 (Read/Write Multiple Registers):
      Data[0..1] = Read start address
      Data[2..3] = Read quantity
      Data[4..5] = Write start address
      Data[6..7] = Write quantity
      Data[8]    = Write byte count (n)
      Data[9..8+n] = Write values (not shown in the description for brevity) }
function GenerateRequestDescription(APkt: TModbusPacket): string;
var
  StartAddr, Quantity, Addr, Value: Word;
  ByteCount, MaxBytes, MaxRegs, I:  Integer;
  State: string;
begin
  Result := '';

  { All supported request frames require at least 4 data bytes
    (start address + quantity, or output address + value) }
  if Length(APkt.Data) < 4 then Exit;

  case APkt.FunctionCode of

    { ── FC 01 / 02 / 03 / 04 — Read requests ── }
    FUNC_READ_COILS,
    FUNC_READ_DISCRETE_INPUTS,
    FUNC_READ_HOLDING_REGS,
    FUNC_READ_INPUT_REGS:
    begin
      StartAddr := BigEndianWord(APkt.Data, 0);   { first register/coil to read }
      Quantity  := BigEndianWord(APkt.Data, 2);   { how many to read }
      Result    := Format(' | Start: 0x%.4X, Qty: %d', [StartAddr, Quantity]);
    end;

    { ── FC 05 — Write Single Coil ── }
    FUNC_WRITE_SINGLE_COIL:
    begin
      Addr  := BigEndianWord(APkt.Data, 0);   { coil address }
      Value := BigEndianWord(APkt.Data, 2);   { 0xFF00 = ON, 0x0000 = OFF }
      if Value = $FF00 then
        State := 'ON'
      else if Value = $0000 then
        State := 'OFF'
      else
        State := Format('0x%04X', [Value]);   { non-standard value — show raw }
      Result := Format(' | Addr: 0x%.4X, Value: %s', [Addr, State]);
    end;

    { ── FC 06 — Write Single Register ── }
    FUNC_WRITE_SINGLE_REG:
    begin
      Addr   := BigEndianWord(APkt.Data, 0);   { register address }
      Value  := BigEndianWord(APkt.Data, 2);   { new value (decimal display) }
      Result := Format(' | Addr: 0x%.4X, Value: %d', [Addr, Value]);
    end;

    { ── FC 15 (0x0F) — Write Multiple Coils ── }
    FUNC_WRITE_MULTIPLE_COILS:
    begin
      if Length(APkt.Data) >= 5 then
      begin
        StartAddr := BigEndianWord(APkt.Data, 0);
        Quantity  := BigEndianWord(APkt.Data, 2);
        ByteCount := APkt.Data[4];              { number of data bytes that follow }
        Result    := Format(' | Start: 0x%.4X, Qty: %d, Bytes: %d',
                            [StartAddr, Quantity, ByteCount]);

        { Show the raw coil bytes as hex — up to 20 bytes to keep it readable }
        if (Length(APkt.Data) > 5) and (ByteCount > 0) then
        begin
          MaxBytes := ByteCount;
          if MaxBytes > 20 then MaxBytes := 20;
          if Length(APkt.Data) >= 5 + MaxBytes then
          begin
            Result := Result + ' | Coils: ';
            for I := 0 to MaxBytes - 1 do
            begin
              if I > 0 then Result := Result + ' ';
              Result := Result + Format('%.2X', [APkt.Data[5 + I]]);
            end;
            if ByteCount > MaxBytes then Result := Result + '...';
          end;
        end;
      end;
    end;

    { ── FC 16 (0x10) — Write Multiple Registers ── }
    FUNC_WRITE_MULTIPLE_REGS:
    begin
      if Length(APkt.Data) >= 5 then
      begin
        StartAddr := BigEndianWord(APkt.Data, 0);
        Quantity  := BigEndianWord(APkt.Data, 2);
        ByteCount := APkt.Data[4];              { = Quantity × 2 bytes }
        Result    := Format(' | Start: 0x%.4X, Qty: %d, Bytes: %d',
                            [StartAddr, Quantity, ByteCount]);

        { Decode register values as decimal integers — up to 20 registers }
        if (Length(APkt.Data) > 5) and (ByteCount >= 2) then
        begin
          MaxRegs := ByteCount div 2;
          if MaxRegs > 20 then MaxRegs := 20;
          Result := Result + ' | Values: ';
          I := 0;
          { Boundary check: 5 + I*2 + 1 < Length ensures both bytes are present }
          while (I < MaxRegs) and ((5 + I * 2 + 1) < Length(APkt.Data)) do
          begin
            if I > 0 then Result := Result + ' ';
            Result := Result + IntToStr(BigEndianWord(APkt.Data, 5 + I * 2));
            Inc(I);
          end;
          if ByteCount div 2 > MaxRegs then Result := Result + '...';
        end;
      end;
    end;

    { ── FC 23 (0x17) — Read/Write Multiple Registers ── }
    FUNC_READ_WRITE_REGS:
    begin
      { Minimum 9 data bytes: ReadStart(2) + ReadQty(2) + WriteStart(2)
        + WriteQty(2) + WriteByteCount(1) }
      if Length(APkt.Data) >= 9 then
        Result := Format(' | Read: %d:%d, Write: %d:%d, Bytes: %d', [
          BigEndianWord(APkt.Data, 0),   { read start address }
          BigEndianWord(APkt.Data, 2),   { read quantity }
          BigEndianWord(APkt.Data, 4),   { write start address }
          BigEndianWord(APkt.Data, 6),   { write quantity }
          APkt.Data[8]]);               { write byte count }
      { Note: write values (Data[9..]) are not shown to keep the description
        concise.  They are visible in the Raw Bytes dump in the detail panel. }
    end;

  end; { case }
end;

{ =============================================================================
  GenerateResponseDescription  (private)
  =============================================================================
  Builds the payload portion of the Description string for RX (slave response)
  frames.  Returns '' for an empty Data field or unsupported function codes.

  Data field layout per function code:

    FC 01/02 (Read Coils / Read Discrete Inputs response):
      Data[0]      = Byte count (n)
      Data[1..n]   = Coil/input status, packed LSB-first, 1 bit per coil.
                     Displayed as raw hex bytes (not decoded to individual bits)
                     because the number of valid bits depends on the request.

    FC 03/04 (Read Holding / Input Registers response):
      Data[0]      = Byte count (n = register count × 2)
      Data[1..n]   = Register values as big-endian 16-bit pairs.
                     Displayed as decimal integers.

    FC 05 (Write Single Coil response):
      Echo of the request: Data[0..1] = coil address, Data[2..3] = value.
      Confirms the write was accepted.

    FC 06 (Write Single Register response):
      Echo of the request: Data[0..1] = register address, Data[2..3] = value.

    FC 15/0F (Write Multiple Coils response):
      Data[0..1] = Start address
      Data[2..3] = Quantity of coils written.
      (Write data is not echoed — only the affected range is confirmed.)

    FC 16/10 (Write Multiple Registers response):
      Same structure as FC 15 response.

    FC 23/17 (Read/Write Multiple Registers response):
      Data[0]      = Byte count (n = read register count × 2)
      Data[1..n]   = Read register values as big-endian 16-bit pairs.
      (The write portion of the command is not echoed in the response.) }
function GenerateResponseDescription(APkt: TModbusPacket): string;
var
  ByteCount, NumRegs, MaxRegs, MaxBytes, I: Integer;
  Addr, Value: Word;
  State: string;
begin
  Result := '';
  if Length(APkt.Data) = 0 then Exit;

  case APkt.FunctionCode of

    { ── FC 01 / 02 — Read Coils / Discrete Inputs response ── }
    FUNC_READ_COILS,
    FUNC_READ_DISCRETE_INPUTS:
    begin
      ByteCount := APkt.Data[0];   { number of status bytes that follow }
      Result := Format(' | Bytes: %d', [ByteCount]);

      { Show raw coil/input bytes as hex — individual bit decoding omitted
        because the request quantity determines which bits are valid }
      if (Length(APkt.Data) > 1) and (ByteCount > 0) then
      begin
        MaxBytes := ByteCount;
        if MaxBytes > 20 then MaxBytes := 20;
        if Length(APkt.Data) >= 1 + MaxBytes then
        begin
          Result := Result + ' | Status: ';
          for I := 0 to MaxBytes - 1 do
          begin
            if I > 0 then Result := Result + ' ';
            Result := Result + Format('%.2X', [APkt.Data[1 + I]]);
          end;
          if ByteCount > MaxBytes then Result := Result + '...';
        end;
      end;
    end;

    { ── FC 03 / 04 / 23 — Read Holding/Input/Write Registers response ── }
    FUNC_READ_HOLDING_REGS,
    FUNC_READ_INPUT_REGS,
    FUNC_READ_WRITE_REGS:
    begin
      ByteCount := APkt.Data[0];   { = register count × 2 }
      Result := Format(' | Bytes: %d', [ByteCount]);

      if (Length(APkt.Data) > 1) and (ByteCount >= 2) then
      begin
        NumRegs := ByteCount div 2;   { total number of registers in response }
        MaxRegs := NumRegs;

        { FC 23 responses can be long; cap at 4 to keep the description terse.
          FC 03/04 responses are capped at 20 registers. }
        if APkt.FunctionCode = FUNC_READ_WRITE_REGS then
        begin
          if MaxRegs > 4 then MaxRegs := 4;
        end
        else
          if MaxRegs > 20 then MaxRegs := 20;

        Result := Result + ' | Values: ';
        I := 0;
        { Boundary check: 1 + I*2 + 1 < Length ensures both bytes are present }
        while (I < MaxRegs) and ((1 + I * 2 + 1) < Length(APkt.Data)) do
        begin
          if I > 0 then Result := Result + ' ';
          Result := Result + IntToStr(BigEndianWord(APkt.Data, 1 + I * 2));
          Inc(I);
        end;
        if NumRegs > MaxRegs then Result := Result + '...';
      end;
    end;

    { ── FC 05 / 06 — Write Single Coil / Register response (echo) ── }
    FUNC_WRITE_SINGLE_COIL,
    FUNC_WRITE_SINGLE_REG:
    begin
      { Successful write: slave echoes the request exactly.
        Confirmed by isResponseToRequest in UModbusSniffer. }
      if Length(APkt.Data) >= 4 then
      begin
        Addr  := BigEndianWord(APkt.Data, 0);
        Value := BigEndianWord(APkt.Data, 2);
        if APkt.FunctionCode = FUNC_WRITE_SINGLE_COIL then
        begin
          if Value = $FF00 then State := 'ON' else State := 'OFF';
          Result := Format(' | Addr: 0x%.4X, State: %s', [Addr, State]);
        end
        else
          Result := Format(' | Addr: 0x%.4X, Value: %d', [Addr, Value]);
      end;
    end;

    { ── FC 15 / 16 — Write Multiple Coils / Registers response ── }
    FUNC_WRITE_MULTIPLE_COILS,
    FUNC_WRITE_MULTIPLE_REGS:
    begin
      { Response confirms only the start address and quantity affected;
        the write data is not echoed back. }
      if Length(APkt.Data) >= 4 then
        Result := Format(' | Start: 0x%.4X, Qty: %d', [
          BigEndianWord(APkt.Data, 0),
          BigEndianWord(APkt.Data, 2)]);
    end;

  end; { case }
end;

{ =============================================================================
  GenerateDescription  (private)
  =============================================================================
  Assembles the complete Description string for a TModbusPacket by combining:
    1. The slave address in hex: "Addr: 0x01"
    2a. For exception responses: " | Exception: 0xNN (Name)"
    2b. For normal frames: " | Function Name" + request or response details

  Parameters:
    APkt       — the partially populated packet (Address, FunctionCode,
                 IsException, ExceptionCode, and Data must already be set)
    ADirection — 'TX' or 'RX', selects the appropriate detail builder

  This function is the only caller of GenerateRequestDescription and
  GenerateResponseDescription.  It is called last in ParsePacket after all
  protocol fields have been extracted. }
function GenerateDescription(APkt: TModbusPacket; const ADirection: string): string;
begin
  { Always start with the slave address }
  Result := Format('Addr: 0x%.2X', [APkt.Address]);

  if APkt.IsException then
    { Exception response — show code and name, no payload details }
    Result := Result + Format(' | Exception: 0x%.2X (%s)',
                [APkt.ExceptionCode, GetExceptionName(APkt.ExceptionCode)])
  else
  begin
    { Normal frame — append function name then direction-specific details }
    Result := Result + ' | ' + GetFunctionName(APkt.FunctionCode);
    if ADirection = 'TX' then
      Result := Result + GenerateRequestDescription(APkt)
    else
      Result := Result + GenerateResponseDescription(APkt);
  end;
end;

{ =============================================================================
  ParsePacket  (public)
  =============================================================================
  The single exported function of this unit.  Parses AData into a new
  TModbusPacket, populating all fields in this order:

    1. Metadata:      Timestamp, Direction, Length
    2. Wire bytes:    Raw (deep copy of AData), HexString
    3. Short-frame check: < 4 bytes → set error Description, return early
    4. Protocol:      Address, FunctionCode
    5. Exception:     if FunctionCode AND 0x80 ≠ 0 → set IsException,
                      ExceptionCode, mask FunctionCode
    6. Payload:       Data = AData[2 .. Len-3]  (excludes addr, func, CRC)
    7. CRC:           compute CRC16 over AData[0..Len-3], extract stored CRC,
                      set ValidCRC
    8. Description:   GenerateDescription(Pkt, ADirection)

  The Raw copy is made with Move (block memory copy) rather than a loop for
  efficiency.  The Data slice is similarly copied with Move. }
function ParsePacket(const AData: TByteArray; const ADirection: string): TModbusPacket;
var
  Pkt:     TModbusPacket;
  Len:     Integer;
  DataLen: Integer;
  CalcCRC: Word;
begin
  Pkt            := TModbusPacket.Create;
  Pkt.Timestamp  := FormatTimestamp(Now);   { capture time — set immediately }
  Pkt.Direction  := ADirection;
  Len            := Length(AData);
  Pkt.Length     := Len;

  { ── Step 2: deep copy of raw bytes ── }
  SetLength(Pkt.Raw, Len);
  if Len > 0 then
    Move(AData[0], Pkt.Raw[0], Len);       { block copy, faster than element loop }

  Pkt.HexString := BytesToHex(AData);      { "AA BB CC …" display string }

  { ── Step 3: short-frame guard ── }
  if Len < 4 then
  begin
    { Frame is too short to contain address + function + CRC.
      Still return a packet so the caller can log and count the anomaly. }
    Pkt.Description := Format('Invalid packet (too short: %d bytes)', [Len]);
    Result := Pkt;
    Exit;
  end;

  { ── Step 4: address and function code ── }
  Pkt.Address      := AData[0];
  Pkt.FunctionCode := AData[1];

  { ── Step 5: exception detection ──
    In a Modbus RTU exception response the slave sets bit 7 of the function
    code byte (i.e. adds 0x80).  For example, an exception to FC 03 (0x03)
    is transmitted as 0x83.
    We store the unmasked code (AND 0x7F) in FunctionCode so the description
    builder can look up the original function name. }
  if (Pkt.FunctionCode and $80) <> 0 then
  begin
    Pkt.IsException   := True;
    Pkt.ExceptionCode := Pkt.FunctionCode and $7F;   { exception code byte }
    Pkt.FunctionCode  := Pkt.FunctionCode and $7F;   { original function code }
  end;

  { ── Step 6: payload extraction ──
    Data occupies bytes 2..Len-3 (everything after func and before CRC).
    DataLen = Len - 4 because we exclude: Addr(1) + Func(1) + CRC_Lo(1) + CRC_Hi(1).
    DataLen may be 0 for minimal frames (e.g. exception responses are 5 bytes:
    Addr + Func|0x80 + ExCode + CRC_Lo + CRC_Hi → DataLen = 1, not 0;
    actually FC 05/06 echo responses are 8 bytes → DataLen = 4). }
  DataLen := Len - 4;
  if DataLen > 0 then
  begin
    SetLength(Pkt.Data, DataLen);
    Move(AData[2], Pkt.Data[0], DataLen);   { AData[2] = first payload byte }
  end;
  { If DataLen = 0, Pkt.Data remains the zero-length array set in the
    constructor, and GenerateResponseDescription will exit early. }

  { ── Step 7: CRC validation ──
    CalcCRC is computed over all bytes except the last two (the CRC itself).
    The stored CRC is read as a little-endian Word from the last two bytes. }
  CalcCRC      := CRC16(AData, Len - 2);
  Pkt.CRC      := LittleEndianWord(AData, Len - 2);
  Pkt.ValidCRC := (CalcCRC = Pkt.CRC);

  { ── Step 8: description ── }
  Pkt.Description := GenerateDescription(Pkt, ADirection);

  Result := Pkt;
end;

end.

