unit UModbusSniffer;

{$mode objfpc}{$H+}

{ =============================================================================
  UModbusSniffer — Modbus RTU frame assembler and direction detector
  =============================================================================

  DISCLAIMER: All documentation was generated by Antropic's Claude Sonnet 4.6

  PURPOSE
  ───────
  This unit implements TModbusAssembler, which sits between the raw serial
  byte stream (delivered by LazSerial) and the packet display (UMain).
  Its two responsibilities are:

    1. FRAME ASSEMBLY
       Accumulate raw bytes into a ring buffer and scan for complete Modbus
       RTU frames using CRC-16 validation as the frame boundary detector.

    2. DIRECTION DETECTION
       Classify each frame as 'TX' (master request) or 'RX' (slave response)
       using a four-rule heuristic that does not require a hardware signal
       or two separate serial ports.

  INTEGRATION WITH LazSerial AND UMain
  ──────────────────────────────────────

    ┌──────────────────────────────────────────────────────────────────┐
    │  LazSerial reader thread                                         │
    │  (internal to TLazSerial — not created by this unit)             │
    └────────────────────┬─────────────────────────────────────────────┘
                         │ Synchronize → fires OnRxData on the main thread
                         ▼
    ┌──────────────────────────────────────────────────────────────────┐
    │  UMain.LazSerial1RxData                                          │
    │    FTimerFrame.Enabled := False; FTimerFrame.Enabled := True;    │
    │    FAssembler.PushBytes(LazSerial1.ReadData);                    │
    └────────────────────┬─────────────────────────────────────────────┘
                         │ PushBytes
                         ▼
    ┌──────────────────────────────────────────────────────────────────┐
    │  TModbusAssembler.FBuf  (512-byte ring buffer, grows if needed)  │
    │  TryExtract: scans for CRC-valid prefix → DispatchFrame          │
    └────────────────────┬─────────────────────────────────────────────┘
                         │ OnPacket callback
                         ▼
    ┌──────────────────────────────────────────────────────────────────┐
    │  UMain.OnPacketReady  → FPackets, FPendingRows                   │
    └──────────────────────────────────────────────────────────────────┘

    Inter-frame gap:
    UMain creates FTimerFrame (interval = 3.5 char times at current baud).
    It is reset on every PushBytes call and fires Flush when the line
    goes silent for one full gap period.

  TIMING — WHY GetTickCount64 INSTEAD OF TDateTime
  ──────────────────────────────────────────────────
  At 115 200 baud one character time is ~0.095 ms, so the Modbus RTU
  inter-frame gap is only ~0.33 ms.  TDateTime has a resolution of ~1 ms on
  Windows (limited by the system clock tick) and involves floating-point
  arithmetic, making sub-millisecond comparisons unreliable.

  GetTickCount64 returns the system uptime in whole milliseconds as a QWord
  (64-bit unsigned integer).  Advantages over TDateTime / Now:
    • Monotonic — never goes backwards (immune to NTP sync, DST changes)
    • Integer arithmetic — no floating-point rounding errors
    • Cheaper to call — no TDateTime conversion overhead
    • Unambiguous subtraction: Tick200 := GetTickCount64 - 200  (plain QWord)

  Resolution is still ~1 ms on Windows.  For true sub-millisecond timing,
  QueryPerformanceCounter (Windows) or clock_gettime(CLOCK_MONOTONIC) (Linux)
  would be required, but the direction-detection thresholds of 200 ms and
  500 ms are already well above the 1 ms timer grain, so GetTickCount64 is
  sufficient and portable across all LCL target platforms.

  THREAD SAFETY
  ─────────────
  All public methods (PushBytes, Flush) are called exclusively from the
  main LCL thread.  LazSerial uses Synchronize internally, so OnRxData
  (and therefore PushBytes) always executes on the main thread.
  No mutexes, critical sections, or TThreadList objects are needed here.

  FRAME EXTRACTION ALGORITHM
  ──────────────────────────
  Modbus RTU has no explicit start-of-frame marker.  Frames are delimited
  only by a silence gap on the line (≥ 3.5 character times).  Within a
  continuous stream the assembler uses CRC validation as a proxy:

    For length = 4, 5, 6, … up to min(FBufLen, 256):
      If IsValidCRC(FBuf[0..length-1]) → this is a complete frame.
      Dispatch it, shift the remaining bytes to the front, recurse.

  This "shortest valid prefix" approach is correct because:
    • Any valid Modbus frame must end with a correct CRC.
    • The probability of a random byte sequence passing CRC-16 is 1/65536.
    • False positives are possible in theory but extremely rare in practice.

  The recursion after a successful extract handles back-to-back frames that
  arrived in the same OnRxData call (common at high baud rates).

  DIRECTION DETECTION — FOUR RULES (applied in priority order)
  ─────────────────────────────────────────────────────────────
  Without separate TX/RX hardware lines the sniffer cannot know with
  certainty which device sent a frame.  These heuristics are applied in
  order; the first match wins:

  Rule 1 — Pending-request match:
    After every TX frame is dispatched, its address, function code, and
    raw bytes are stored in FPending[address].  When the next frame
    arrives with the same slave address and a function code and length
    consistent with a valid response to that request → classify as RX.
    Window: 500 ms.  After that the pending entry is considered stale.

  Rule 2 — Quick follow-up after TX:
    If the most recent dispatched frame was TX and this frame arrived
    within 200 ms → classify as RX.
    Rationale: a slave response always follows the master request closely.

  Rule 3 — Long idle → new TX:
    If more than 500 ms has elapsed since any frame → classify as TX.
    Rationale: a Modbus master initiates every cycle; long silence means
    the bus is idle and the next frame must be a new master request.

  Rule 4 — Structural heuristic:
    Certain frame lengths are unique to request frames for a given
    function code (e.g. all FC 01–06 requests are exactly 8 bytes).
    If the frame matches one of these patterns → classify as TX.

  PENDING REQUEST TABLE
  ──────────────────────
  FPending is a fixed-size array indexed by slave address (0–247).
  This is safe because the Modbus specification limits slave addresses to
  1–247 (0 = broadcast, 248–255 reserved).  Using a direct-index array
  instead of a TList avoids heap allocation on every request and gives O(1)
  lookup and update.

  The Valid flag avoids acting on uninitialised entries.  TrackRequest sets
  Valid := True; ClearPending sets Valid := False.

  ============================================================================= }

interface

uses
  Classes,       { TObject }
  SysUtils,      { IfThen, CompareMem }
  UModbusTypes,  { TModbusPacket, TByteArray, FUNC_* }
  UModbusUtils,  { IsValidCRC }
  UModbusParser; { ParsePacket }

type

  { ── TPendingRequest ─────────────────────────────────────────────────────
    Stores the context of the most recent TX frame sent to one slave address.
    Used by IsResponseToRequest and DetectDirection (Rule 1).

    Fields:
      Data      — full raw bytes of the TX frame (copy, owned by this record)
      Timestamp — tick count (ms) when the TX frame was dispatched,
                  obtained from GetTickCount64.  Used for the 500 ms expiry
                  window in DetectDirection Rule 1.  QWord arithmetic avoids
                  the floating-point precision issues of TDateTime at high
                  baud rates.
      FuncCode  — function code of the TX frame (lower 7 bits, exception bit clear)
      IsWrite   — True if FuncCode is a write operation (FC 05,06,0F,10,16)
      Valid     — True if this slot contains a live, unexpired request.
                  False at startup and after ClearPending; prevents stale
                  entries from being mistakenly matched. }

  TPendingRequest = record
    Data:      TByteArray;
    Timestamp: QWord;     { GetTickCount64 value at dispatch time (milliseconds) }
    FuncCode:  Byte;
    IsWrite:   Boolean;
    Valid:     Boolean;
  end;

  { ── TPacketCallback ─────────────────────────────────────────────────────
    Method pointer type for the OnPacket event.
    Called by DispatchFrame after a complete frame has been parsed.
    The TModbusPacket is freshly allocated; ownership transfers to the
    callback handler (UMain.OnPacketReady), which adds it to FPackets.
    If no callback is assigned, the packet is freed immediately. }

  TPacketCallback = procedure(APkt: TModbusPacket) of object;

  { ── TModbusAssembler ────────────────────────────────────────────────────
    Stateful byte-stream-to-frame converter.
    All public methods must be called from the main LCL thread only. }

  TModbusAssembler = class
  private

    { ── Assembly buffer ── }

    FBuf: TByteArray;
    { Ring buffer that accumulates raw bytes from PushBytes.
      Allocated to 512 bytes at construction; grown automatically by
      PushBytes if the incoming string would overflow.
      Only FBuf[0..FBufLen-1] contains valid data. }

    FBufLen: Integer;
    { Number of valid bytes currently in FBuf.
      Reset to 0 after a successful frame extraction (shift-left) or Flush. }

    { ── Pending request table ── }

    FPending: array[0..247] of TPendingRequest;
    { Direct-indexed by slave address (0–247).
      Slot N is "live" when FPending[N].Valid = True and
      GetTickCount64 - FPending[N].Timestamp < 500 (ms, integer arithmetic).
      Updated by TrackRequest (on TX dispatch) and ClearPending (on RX match). }

    { ── Direction-tracking state ── }

    FLastDirection: string;
    { Direction of the most recently dispatched frame ('TX' or 'RX').
      Initialised to 'TX' on the assumption that the master sends first.
      Used by DetectDirection Rule 2. }

    FLastPktTime: QWord;
    { GetTickCount64 value (ms) when the most recently dispatched frame
      was processed.  Initialised to GetTickCount64 at construction.
      Used by DetectDirection Rules 2 and 3.  QWord subtraction is safe
      even on wrap-around (after ~49 days) because unsigned arithmetic
      handles the modulo correctly. }

    { ── Callback ── }

    FOnPacket: TPacketCallback;
    { Set by UMain: FAssembler.OnPacket := @OnPacketReady.
      Called from DispatchFrame after each complete frame is parsed. }

    { ── Private helpers ── }

    function IsWriteFunc(AFunc: Byte): Boolean;
    { Returns True for FC 05, 06, 0F, 10, 16 — the write operations.
      Used when storing a pending request to set the IsWrite flag.
      FC 16 (0x16 = Mask Write Register) is included even though it is not
      in the FUNC_* display set, because it produces an echo response. }

    function IsLikelyRequest(const AData: TByteArray; ALen: Integer): Boolean;
    { Structural heuristic (Direction Rule 4).
      Returns True when the frame length matches the fixed request format
      for its function code:
        FC 01–06: exactly 8 bytes (Addr + Func + StartAddr(2) + Qty(2) + CRC(2))
        FC 0F/10: 7 + ByteCount + 2 bytes (variable-length write)
        FC 17:    9 + WriteByteCount + 2 bytes
        FC 07,08,0B,0C,11,14,15,18,2B: request-only codes, always True
      Returns False for any other length or unknown function code. }

    function IsResponseToRequest(const AResp: TByteArray; ALen: Integer;
                                  var APend: TPendingRequest): Boolean;
    { Validates that AResp is a plausible response to the tracked request
      APend, using function-code-specific length checks:
        FC 01–04: length = 3 + ByteCount + 2 (byte count is AResp[2])
        FC 05,06: exact byte-for-byte echo of the request (CompareMem)
        FC 0F,10: first 6 bytes match the request (address + function +
                  start address + quantity)
        FC 17:    any CRC-valid frame with matching function code
      Returns False immediately if the function codes do not match. }

    function DetectDirection(const AData: TByteArray; ALen: Integer): string;
    { Applies the four direction-detection rules in priority order and
      returns 'TX' or 'RX'.  Default is 'RX'.
      Short frames (< 4 bytes) and frames with a bad CRC default to 'RX'.
      Exception frames (bit 7 of function code set) are always 'RX'. }

    procedure TrackRequest(AAddr, AFunc: Byte;
                           const AData: TByteArray; ALen: Integer);
    { Records a TX frame in FPending[AAddr] for future response matching.
      Called by DispatchFrame for every TX frame with a normal (non-exception)
      function code.  Copies ALen bytes of AData into the record. }

    procedure ClearPending(AAddr: Byte);
    { Marks FPending[AAddr].Valid := False after a matching RX frame arrives,
      preventing the same request from matching a second response. }

    procedure TryExtract;
    { Scans FBuf[0..FBufLen-1] for the shortest valid Modbus RTU frame
      (minimum 4 bytes) using IsValidCRC.  On success:
        1. Dispatches the frame via DispatchFrame.
        2. Shifts remaining bytes left in FBuf (Move).
        3. Recurses to check for additional back-to-back frames.
      Does nothing if FBufLen < 4. }

    procedure DispatchFrame(const AData: TByteArray; ALen: Integer;
                            const ADir: string);
    { Parses AData into a TModbusPacket via ParsePacket, updates pending
      request tracking, updates FLastDirection/FLastPktTime, then fires
      FOnPacket.  If FOnPacket is not assigned the packet is freed here
      to avoid a memory leak. }

  public

    constructor Create;
    { Initialises FBuf to 512 bytes, sets FBufLen := 0, FLastDirection := 'TX',
      FLastPktTime := GetTickCount64, and clears all FPending[].Valid flags. }

    destructor Destroy; override;
    { Releases FBuf. }

    procedure PushBytes(const AStr: string);
    { Appends the bytes of AStr to FBuf, growing FBuf if necessary, then
      calls TryExtract to check for newly completable frames.

      AStr is the raw string returned by LazSerial1.ReadData.  Each character
      is interpreted as a single byte (Byte(AStr[I])), which is correct
      because LazSerial returns an AnsiString of raw octets, not UTF-16.

      If AStr is empty the method returns immediately without touching FBuf. }

    procedure Flush;
    { Forces the contents of FBuf to be dispatched as a single frame,
      regardless of whether a valid CRC was found.

      Called by UMain.TimerFrameTimer when the inter-frame gap timer fires,
      indicating that no bytes have arrived for ≥ 3.5 character times.
      The Modbus RTU specification defines this silence as a frame boundary,
      so whatever is in the buffer at that point is a complete frame
      (possibly with errors).

      Resets FBufLen to 0 after dispatching. }

    property OnPacket: TPacketCallback read FOnPacket write FOnPacket;
    { Set this to the form's packet handler before starting capture:
        FAssembler.OnPacket := @OnPacketReady;
      The callback receives ownership of the TModbusPacket. }

  end;

implementation

uses
  Math;  { Min() used in TryExtract to cap scan length at 256 bytes }

{ =============================================================================
  Constructor / Destructor
  ============================================================================= }

constructor TModbusAssembler.Create;
var
  I: Integer;
begin
  inherited Create;
  SetLength(FBuf, 512);       { initial buffer — fits any realistic burst }
  FBufLen        := 0;
  FLastDirection := 'TX';     { assume master sends first }
  FLastPktTime   := GetTickCount64;
  { Mark all pending slots as invalid so DetectDirection Rule 1 cannot
    fire before any TX frame has been seen }
  for I := 0 to 247 do
    FPending[I].Valid := False;
end;

destructor TModbusAssembler.Destroy;
begin
  SetLength(FBuf, 0);
  inherited Destroy;
end;

{ =============================================================================
  Public API
  ============================================================================= }

procedure TModbusAssembler.PushBytes(const AStr: string);
{ Appends each character of AStr as a raw byte to FBuf.
  Grows FBuf by 256 extra bytes when the buffer would overflow, to amortise
  future reallocations.  Calls TryExtract after appending so that frames
  are identified and dispatched as early as possible within a single
  OnRxData call. }
var
  I, Need: Integer;
begin
  if AStr = '' then Exit;
  Need := FBufLen + Length(AStr);
  if Need > Length(FBuf) then
    SetLength(FBuf, Need + 256);      { over-allocate to minimise future grows }
  for I := 1 to Length(AStr) do
  begin
    FBuf[FBufLen] := Byte(AStr[I]);   { AnsiString: each char is one byte }
    Inc(FBufLen);
  end;
  TryExtract;
end;

procedure TModbusAssembler.Flush;
{ Called when the inter-frame gap timer fires.
  The silence means the current FBuf contents form a complete frame —
  even if IsValidCRC would not find a valid CRC (e.g. corrupt frame).
  A copy of the buffer is taken before resetting FBufLen so that
  DispatchFrame receives a stable slice. }
var
  Slice: TByteArray = nil;
begin
  if FBufLen = 0 then Exit;
  SetLength(Slice, FBufLen);
  Move(FBuf[0], Slice[0], FBufLen);
  FBufLen := 0;
  DispatchFrame(Slice, Length(Slice), DetectDirection(Slice, Length(Slice)));
end;

{ =============================================================================
  Frame extraction
  ============================================================================= }

procedure TModbusAssembler.TryExtract;
{ Shortest-valid-prefix scan.
  The outer loop tries every possible frame length from 4 to Min(FBufLen,256).
  256 is the maximum Modbus RTU frame size (Addr(1) + Func(1) + Data(252)
  + CRC(2) = 256 bytes).

  When a valid CRC is found:
    • DispatchFrame is called with a copy of FBuf[0..I-1].
    • The consumed bytes are removed from FBuf using a left-shift Move.
    • FBufLen is decremented.
    • TryExtract recurses to handle any additional complete frames that
      may have accumulated (common when multiple frames arrive in one
      OnRxData call at high baud rates).
    • Exit is called to prevent the outer loop from continuing after the
      recursion (the buffer state has changed).

  If no CRC-valid prefix is found the method returns without modifying the
  buffer — more bytes are needed before a complete frame can be extracted. }
var
  I, MaxLen: Integer;
  Candidate: TByteArray;
  Dir:       string;
begin
  if FBufLen < 4 then Exit;     { need at least Addr + Func + CRC(2) }
  MaxLen    := Min(FBufLen, 256);
  Candidate := nil;             { pre-initialise managed type }

  I := 4;
  while I <= MaxLen do
  begin
    SetLength(Candidate, I);
    Move(FBuf[0], Candidate[0], I);

    if IsValidCRC(Candidate) then
    begin
      Dir := DetectDirection(Candidate, I);
      DispatchFrame(Candidate, I, Dir);

      { Remove the consumed bytes from the front of the buffer }
      if FBufLen > I then
        Move(FBuf[I], FBuf[0], FBufLen - I);
      Dec(FBufLen, I);

      TryExtract;   { recursively check for more complete frames }
      Exit;
    end;
    Inc(I);
  end;
end;

procedure TModbusAssembler.DispatchFrame(const AData: TByteArray; ALen: Integer;
                                          const ADir: string);
{ Central dispatch point — called for every complete (or timeout-forced) frame.

  Sequence:
    1. Guard: ignore zero-length frames (defensive; should not occur normally).
    2. Parse: ParsePacket creates a TModbusPacket from AData and ADir.
    3. Track TX: if this is a TX frame with a normal function code, store it
       in FPending so the next frame to/from the same slave can be matched
       as a response (Direction Rule 1).
    4. Clear RX: if this is an RX frame, mark the pending slot for that
       slave as invalid (the request-response cycle is complete).
    5. Update state: record FLastDirection and FLastPktTime for Rules 2 and 3.
    6. Fire callback: pass ownership of the TModbusPacket to FOnPacket.
       If no callback is set, free the packet immediately to avoid a leak.

  Note on IfThen for Func:
    IfThen(ALen >= 2, AData[1], 0) safely reads the function code byte only
    if at least 2 bytes exist, avoiding an array out-of-bounds access for
    the degenerate 1-byte frame edge case. }
var
  Pkt:        TModbusPacket;
  Addr, Func: Byte;
begin
  if ALen = 0 then Exit;

  Pkt  := ParsePacket(AData, ADir);
  Addr := AData[0];
  Func := IfThen(ALen >= 2, AData[1], 0);

  { Track TX requests for Rule 1 direction matching }
  if (ADir = 'TX') and (ALen >= 2) and ((Func and $80) = 0) then
    TrackRequest(Addr, Func, AData, ALen);

  { Clear pending entry when a response arrives }
  if ADir = 'RX' then
    ClearPending(Addr);

  FLastPktTime   := GetTickCount64;
  FLastDirection := ADir;

  if Assigned(FOnPacket) then
    FOnPacket(Pkt)      { ownership of Pkt passes to the callback }
  else
    Pkt.Free;           { no handler → free immediately }
end;

{ =============================================================================
  Direction detection
  ============================================================================= }

function TModbusAssembler.IsWriteFunc(AFunc: Byte): Boolean;
{ Returns True for all function codes that produce an echo response.
  FC 16 (0x16, Mask Write Register) is included here even though it is
  not listed in the FUNC_* display constants, because its response is
  also an echo and therefore IsResponseToRequest must treat it correctly. }
begin
  Result := AFunc in [$05, $06, $0F, $10, $16];
end;

function TModbusAssembler.IsLikelyRequest(const AData: TByteArray;
                                            ALen: Integer): Boolean;
{ Structural heuristic: certain function codes have fixed-length request
  frames that cannot be confused with response frames of the same length.

  Request-only codes (FC 07,08,0B,0C,11,14,15,18,2B) have no corresponding
  response format that would match the same length, so they are always TX.

  For FC 01–06 the request is exactly 8 bytes; responses are variable-length.
  For FC 0F/10 the request length = 7 + ByteCount + 2, derived from AData[6].
  For FC 17 the request length = 9 + WriteByteCount + 2, from AData[8].

  AData[6] and AData[8] are read only after the corresponding length check
  to avoid out-of-range errors. }
var
  Func, BC: Byte;
begin
  Result := False;
  if ALen < 4 then Exit;
  Func := AData[1];

  { Request-only function codes — no corresponding response format }
  if Func in [$07, $08, $0B, $0C, $11, $14, $15, $18, $2B] then
  begin
    Result := True;
    Exit;
  end;

  case Func of
    { FC 01–06: all requests are 8 bytes }
    $01..$06:
      Result := (ALen = 8);

    { FC 0F (Write Multiple Coils): 7 fixed + ByteCount data + 2 CRC }
    $0F, $10:
      if ALen >= 7 then
      begin
        BC     := AData[6];
        Result := (ALen = 7 + BC + 2);
      end;

    { FC 17 (Read/Write Multiple Registers): 9 fixed + WriteByteCount + 2 CRC }
    $17:
      if ALen >= 9 then
      begin
        BC     := AData[8];
        Result := (ALen = 9 + BC + 2);
      end;
  end;
end;

function TModbusAssembler.IsResponseToRequest(const AResp: TByteArray;
                                               ALen: Integer;
                                               var APend: TPendingRequest): Boolean;
{ Checks whether AResp is a valid response to the request stored in APend.
  Matching is done function-code-specific to reduce false positives.

  FC 01–04 (read): response length = 3 + ByteCount + 2.
    AResp[2] is the ByteCount field; the total length must match exactly.

  FC 05,06 (write single): slave echoes the request exactly.
    CompareMem over the full frame ensures both address, function, output
    address, output value, and CRC all match.

  FC 0F,10 (write multiple): slave echoes only the first 6 bytes
    (Addr + Func + StartAddr(2) + Quantity(2)), not the write data.
    CRC is not checked here because the response CRC covers only those 6+2
    bytes, which differ from the request CRC.

  FC 17 (read/write): response is variable-length; any CRC-valid frame with
    a matching function code is accepted.

  Returns False immediately if the function codes do not match (with the
  exception bit stripped from the response function code for exception frames). }
var
  ReqF, RespF: Byte;
  BC:          Integer;
begin
  Result := False;
  ReqF   := APend.FuncCode;
  RespF  := AResp[1];

  { Strip exception bit if present — exception responses are always RX,
    but we still want to match them to their pending request }
  if (RespF and $80) <> 0 then RespF := RespF and $7F;

  if ReqF <> RespF then Exit;   { different function → not a response to this request }

  case ReqF of
    $01, $02, $03, $04:
      if ALen >= 3 then
      begin
        BC     := AResp[2];               { byte count field }
        Result := (ALen = 3 + BC + 2);    { Addr+Func+BC + data + CRC(2) }
      end;

    $05, $06:
      { Response must be byte-for-byte identical to the request }
      if ALen = Length(APend.Data) then
        Result := CompareMem(@AResp[0], @APend.Data[0], ALen);

    $0F, $10:
      { First 6 bytes of response echo the request; rest differs }
      if (ALen >= 6) and (Length(APend.Data) >= 6) then
        Result := CompareMem(@AResp[0], @APend.Data[0], 6);

    $17:
      { Accept any CRC-valid frame with matching function code }
      Result := IsValidCRC(AResp);
  end;
end;

function TModbusAssembler.DetectDirection(const AData: TByteArray;
                                           ALen: Integer): string;
{ Applies the four direction rules in priority order.
  Default return value is 'RX'.

  Timing thresholds use GetTickCount64 (QWord, milliseconds) rather than
  TDateTime / Now.  At 115 200 baud the inter-frame gap is ~0.33 ms, well
  below the ~1 ms resolution of TDateTime.  GetTickCount64 uses integer
  subtraction, is monotonic, and carries no floating-point rounding error.

  Thresholds computed once per call:
    Now200 = GetTickCount64 - 200  → Rule 2 boundary (200 ms ago)
    Now500 = GetTickCount64 - 500  → Rules 1 and 3 boundary (500 ms ago)

  Comparing FLastPktTime > Now200 is equivalent to asking "was the last
  packet within the last 200 ms?", expressed as QWord integer comparison.
  QWord wrap-around (after ~49 days uptime) is handled correctly by unsigned
  subtraction modulo 2^64. }
var
  Addr, Func:     Byte;
  Tick:           QWord;
  Now200, Now500: QWord;
begin
  Result := 'RX';   { conservative default }

  { Pre-conditions: must be at least 4 bytes and have a valid CRC }
  if ALen < 4 then Exit;
  if not IsValidCRC(AData) then Exit;

  Addr := AData[0];
  Func := AData[1];

  { Exception responses (bit 7 set) are always from the slave → always RX }
  if (Func and $80) <> 0 then Exit;

  Tick   := GetTickCount64;
  Now200 := Tick - 200;
  Now500 := Tick - 500;

  { ── Rule 1: does this frame match a tracked pending request? ── }
  if FPending[Addr].Valid and (FPending[Addr].Timestamp > Now500) then
    if IsResponseToRequest(AData, ALen, FPending[Addr]) then
      Exit;   { matched → RX (default), no need to check further rules }

  { ── Rule 2: quick follow-up after a TX frame ── }
  { A slave response always arrives within 200 ms of the master request.
    If we just dispatched a TX and this frame is very quick → RX. }
  if (FLastDirection = 'TX') and (FLastPktTime > Now200) then
    Exit;   { RX }

  { ── Rule 3: long idle → new master request ── }
  { More than 500 ms of silence means the master is starting a new cycle. }
  if FLastPktTime < Now500 then
  begin
    Result := 'TX';
    Exit;
  end;

  { ── Rule 4: structural heuristic ── }
  if IsLikelyRequest(AData, ALen) then
    Result := 'TX';

  { If none of the TX rules fired, Result remains 'RX' (the default). }
end;

{ =============================================================================
  Pending request tracking
  ============================================================================= }

procedure TModbusAssembler.TrackRequest(AAddr, AFunc: Byte;
                                         const AData: TByteArray; ALen: Integer);
{ Stores a TX frame in the pending table so the next frame from/to the same
  slave address can be checked against it in DetectDirection Rule 1.

  Copy(AData, 0, ALen) creates a new dynamic array containing ALen bytes
  starting at index 0, giving the record its own independent copy of the
  frame bytes.  This is important because AData is a local slice in TryExtract
  or Flush that will be overwritten on the next call.

  Timestamp is set to GetTickCount64 (QWord, ms) so DetectDirection can
  compute the 500 ms expiry window with plain integer subtraction. }
begin
  FPending[AAddr].Data      := Copy(AData, 0, ALen);
  FPending[AAddr].Timestamp := GetTickCount64;
  FPending[AAddr].FuncCode  := AFunc;
  FPending[AAddr].IsWrite   := IsWriteFunc(AFunc);
  FPending[AAddr].Valid     := True;
end;

procedure TModbusAssembler.ClearPending(AAddr: Byte);
{ Invalidates the pending request for slave AAddr after a matching response
  has been received.  Setting Valid := False is sufficient — the Data array
  remains allocated but will be overwritten by the next TrackRequest call.
  This is safe because dynamic arrays are reference-counted; no explicit
  free is needed. }
begin
  FPending[AAddr].Valid := False;
end;

end.

