unit UModbusTypes;

{$mode objfpc}{$H+}

{ =============================================================================
  UModbusTypes — Modbus RTU core types, constants, and lookup tables
  =============================================================================

  DISCLAIMER: All documentation was generated by Antropic's Claude Sonnet 4.6

  PURPOSE
  ───────
  This unit is the shared vocabulary for the entire sniffer application.
  It defines:
    • The Modbus function-code constants used by UModbusParser and UMain.
    • TByteArray — the raw byte buffer type passed between all units.
    • TModbusPacket — the central data object that carries one complete
      Modbus RTU frame from the assembler to the UI.
    • GetFunctionName / GetExceptionName — human-readable label lookups
      used by UModbusParser (description builder) and UMain (detail panel).

  DEPENDENCIES
  ────────────
  Intentionally minimal: only the FPC RTL units Classes and SysUtils.
  No LCL, no serial, no parser logic.  Every other unit in the project
  depends on UModbusTypes; UModbusTypes depends on nothing project-specific.

  MODBUS RTU FRAME STRUCTURE (for reference)
  ───────────────────────────────────────────
  Every RTU frame on the wire has the form:

    ┌──────────┬──────────┬─────────────────────┬───────────┐
    │ Address  │ Function │ Data (0–252 bytes)   │ CRC-16    │
    │ 1 byte   │ 1 byte   │ variable             │ 2 bytes   │
    └──────────┴──────────┴─────────────────────┴───────────┘

  • Address:  slave device number 1–247 (0 = broadcast, 248–255 reserved).
  • Function: one of the FUNC_* constants below.  If the high bit (0x80) is
              set it is an exception response; the lower 7 bits are the
              original function code.
  • Data:     content depends on the function code and direction (TX/RX).
  • CRC-16:   polynomial 0xA001 (reflected 0x8005), stored little-endian
              (low byte first, high byte second).

  EXCEPTION RESPONSE FORMAT
  ──────────────────────────
  When a slave cannot execute a request it replies with:

    ┌──────────┬─────────────────┬───────────────┬───────────┐
    │ Address  │ Function | 0x80 │ Exception code │ CRC-16    │
    │ 1 byte   │ 1 byte          │ 1 byte         │ 2 bytes   │
    └──────────┴─────────────────┴───────────────┴───────────┘

  TModbusPacket.IsException = True in this case, FunctionCode holds the
  original (unmasked) code, and ExceptionCode holds the error code.

  ============================================================================= }

interface

uses
  Classes,  { TObject }
  SysUtils; { Format }

{ =============================================================================
  Modbus function code constants
  =============================================================================
  These are the function codes supported by this sniffer.  They correspond
  to the most common Modbus RTU commands used in industrial automation.

  Naming convention: FUNC_<operation>_<object-type>
    READ   = master is requesting data from the slave
    WRITE  = master is sending data to the slave
    COILS  = single-bit read/write outputs (DO — Digital Output)
    DISCRETE_INPUTS = single-bit read-only inputs (DI — Digital Input)
    HOLDING_REGS    = 16-bit read/write registers (AO — Analogue Output)
    INPUT_REGS      = 16-bit read-only registers  (AI — Analogue Input)  }

const
  { FC 01 — Read Coils
    TX: [Addr][01][StartAddr(2)][Quantity(2)][CRC(2)]          (8 bytes)
    RX: [Addr][01][ByteCount(1)][CoilStatus(n)][CRC(2)] }
  FUNC_READ_COILS           = $01;

  { FC 02 — Read Discrete Inputs
    Identical frame format to FC 01 but reads DI (read-only) bits. }
  FUNC_READ_DISCRETE_INPUTS = $02;

  { FC 03 — Read Holding Registers
    TX: [Addr][03][StartAddr(2)][Quantity(2)][CRC(2)]          (8 bytes)
    RX: [Addr][03][ByteCount(1)][RegValues(n*2)][CRC(2)] }
  FUNC_READ_HOLDING_REGS    = $03;

  { FC 04 — Read Input Registers
    Identical frame format to FC 03 but reads AI (read-only) registers. }
  FUNC_READ_INPUT_REGS      = $04;

  { FC 05 — Write Single Coil
    TX: [Addr][05][CoilAddr(2)][Value(2)][CRC(2)]              (8 bytes)
        Value = 0xFF00 → ON,  0x0000 → OFF
    RX: Echo of the request (same 8 bytes). }
  FUNC_WRITE_SINGLE_COIL    = $05;

  { FC 06 — Write Single Register
    TX: [Addr][06][RegAddr(2)][RegValue(2)][CRC(2)]            (8 bytes)
    RX: Echo of the request (same 8 bytes). }
  FUNC_WRITE_SINGLE_REG     = $06;

  { FC 15 (0x0F) — Write Multiple Coils
    TX: [Addr][0F][StartAddr(2)][Quantity(2)][ByteCount(1)][Values(n)][CRC(2)]
    RX: [Addr][0F][StartAddr(2)][Quantity(2)][CRC(2)]          (8 bytes) }
  FUNC_WRITE_MULTIPLE_COILS = $0F;

  { FC 16 (0x10) — Write Multiple Registers
    TX: [Addr][10][StartAddr(2)][Quantity(2)][ByteCount(1)][Values(n*2)][CRC(2)]
    RX: [Addr][10][StartAddr(2)][Quantity(2)][CRC(2)]          (8 bytes) }
  FUNC_WRITE_MULTIPLE_REGS  = $10;

  { FC 23 (0x17) — Read/Write Multiple Registers
    Combines a write and a read in one transaction.
    TX: [Addr][17][ReadStart(2)][ReadQty(2)][WriteStart(2)][WriteQty(2)]
               [ByteCount(1)][WriteValues(n*2)][CRC(2)]
    RX: [Addr][17][ByteCount(1)][ReadValues(n*2)][CRC(2)] }
  FUNC_READ_WRITE_REGS      = $17;

{ =============================================================================
  TByteArray
  =============================================================================
  A dynamic array of bytes used as the raw frame buffer throughout the
  application.  Passed by value (reference-counted) between units, so no
  explicit memory management is required by callers.
  FPC's dynamic arrays are reference-counted and heap-allocated; SetLength
  adjusts the size and initialises new elements to zero. }

type
  TByteArray = array of Byte;

{ =============================================================================
  TModbusPacket
  =============================================================================
  Carries the complete parsed result of one Modbus RTU frame.

  Ownership:
    TModbusPacket objects are created by UModbusSniffer (TModbusAssembler) and
    ownership is transferred to UMain (TfrmMain.FPackets).  FPackets is a TList
    that frees each object in FormDestroy and btnClearClick.

  Field layout follows the order in which fields are populated by the parser:
    1. Transport metadata (Timestamp, Direction, Length)
    2. Wire bytes      (Raw, HexString)
    3. Protocol fields (Address, FunctionCode, IsException, ExceptionCode)
    4. Payload         (Data)
    5. Integrity       (CRC, ValidCRC)
    6. Human text      (Description) }

  TModbusPacket = class
  public

    { ── Transport metadata ── }

    Timestamp: string;
    { Capture time formatted as "HH:MM:SS.mmm" by UModbusUtils.FormatTimestamp.
      Set at parse time (not receive time) so it reflects when the complete
      frame was assembled, not when the first byte arrived. }

    Direction: string;
    { Either 'TX' (master → slave, request) or 'RX' (slave → master, response).
      Determined by TModbusAssembler.DetectDirection using a combination of:
        • Pending-request tracking (does this frame answer a recent TX?)
        • Inter-packet timing (quick follow-up after TX → likely RX)
        • Structural analysis (fixed-length patterns unique to requests) }

    Length: Integer;
    { Total frame length in bytes, including address (1), function (1),
      data payload (variable), and CRC (2).  Equal to Length(Raw). }

    { ── Wire-level representation ── }

    Raw: TByteArray;
    { Complete frame bytes as received from the serial port, including the
      address, function code, data payload, and both CRC bytes.
      Used for the "Raw Bytes" dump in the detail panel. }

    HexString: string;
    { Space-separated uppercase hex representation of Raw, e.g.:
        "01 03 00 00 00 02 C4 0B"
      Generated by UModbusUtils.BytesToHex.  Displayed in the Hex column and
      used as one of the filter search targets in UMain. }

    { ── Protocol fields ── }

    Address: Byte;
    { Modbus slave address extracted from Raw[0].
      Range 1–247 for normal slaves; 0 = broadcast (no response expected);
      248–255 = reserved. }

    FunctionCode: Byte;
    { Modbus function code extracted from Raw[1], with the exception bit
      (0x80) masked out if IsException is True.
      Compare against the FUNC_* constants to identify the operation. }

    IsException: Boolean;
    { True when Raw[1] has bit 7 set (Raw[1] AND 0x80 <> 0), indicating
      that the slave returned an error response instead of normal data.
      When True, ExceptionCode holds the reason and Data is empty. }

    ExceptionCode: Byte;
    { Valid only when IsException = True.
      The exception code byte from Raw[2], identifying the error reason.
      See GetExceptionName for the human-readable mapping. }

    { ── Payload ── }

    Data: TByteArray;
    { The frame payload: everything between the function code byte and the
      two CRC bytes.  Length = frame.Length - 4.
      For request frames: contains start address, quantity, byte count, values.
      For response frames: contains byte count and register/coil values.
      Empty (Length = 0) for exception responses and frames shorter than 5 bytes. }

    { ── Integrity ── }

    CRC: Word;
    { The CRC-16 value stored in the last two bytes of the frame,
      interpreted as little-endian: CRC = Raw[Len-2] OR (Raw[Len-1] SHL 8).
      Displayed as "0xNNNN" in the detail panel. }

    ValidCRC: Boolean;
    { True when the CRC-16 computed over Raw[0..Len-3] equals CRC.
      False frames are displayed in magenta in the grid and counted in
      FErrorCount.  A bad CRC usually indicates noise, baud rate mismatch,
      or a framing error. }

    { ── Human-readable summary ── }

    Description: string;
    { Parsed summary built by UModbusParser.GenerateDescription.  Examples:
        "Addr: 0x01 | Read Holding Registers | Start: 0x0000, Qty: 10"
        "Addr: 0x01 | Read Holding Registers | Bytes: 20 | Values: 100 200 …"
        "Addr: 0x03 | Exception: 0x02 (Illegal Data Address)"
      Displayed in COL_DESC and in the detail panel. }

    constructor Create;
    { Initialises Data and Raw to zero-length dynamic arrays.
      All other fields are zero/empty by default (FPC zero-initialises
      class fields). }

    destructor Destroy; override;
    { Explicitly releases the dynamic arrays before calling inherited Destroy.
      Strictly speaking FPC would release them automatically, but the explicit
      SetLength(X, 0) calls make ownership and lifetime intent clear. }
  end;

{ =============================================================================
  Lookup functions
  ============================================================================= }

function GetFunctionName(AFunc: Byte): string;
{ Returns the standard Modbus name for a function code, e.g.:
    GetFunctionName($03) → 'Read Holding Registers'
  Returns 'Unknown Function (0xNN)' for codes not in the FUNC_* list.
  Called by UModbusParser.GenerateDescription and UMain.ShowPacketDetails. }

function GetExceptionName(ACode: Byte): string;
{ Returns the standard Modbus exception description for an exception code, e.g.:
    GetExceptionName($02) → 'Illegal Data Address'
  Returns 'Unknown Exception (0xNN)' for codes not in the table.
  Called by UModbusParser.GenerateDescription and UMain.ShowPacketDetails. }

implementation

{ =============================================================================
  TModbusPacket
  ============================================================================= }

constructor TModbusPacket.Create;
{ Explicit zero-length initialisation of both dynamic arrays ensures that
  High(Data) = -1 and High(Raw) = -1 immediately after construction,
  so callers can safely use Length() or High() without checking for nil. }
begin
  inherited Create;
  SetLength(Data, 0);
  SetLength(Raw,  0);
end;

destructor TModbusPacket.Destroy;
{ Release dynamic arrays explicitly before inherited so their reference
  counts are decremented here rather than in the base-class finaliser.
  FPC's memory manager will reclaim the heap blocks immediately. }
begin
  SetLength(Data, 0);
  SetLength(Raw,  0);
  inherited Destroy;
end;

{ =============================================================================
  GetFunctionName
  =============================================================================
  Maps a Modbus function code byte to its standard name.
  Uses a case statement rather than a lookup array so that sparse or
  non-contiguous codes ($0F, $10, $17) are handled without wasted entries. }
function GetFunctionName(AFunc: Byte): string;
begin
  case AFunc of
    FUNC_READ_COILS:           Result := 'Read Coils';
    FUNC_READ_DISCRETE_INPUTS: Result := 'Read Discrete Inputs';
    FUNC_READ_HOLDING_REGS:    Result := 'Read Holding Registers';
    FUNC_READ_INPUT_REGS:      Result := 'Read Input Registers';
    FUNC_WRITE_SINGLE_COIL:    Result := 'Write Single Coil';
    FUNC_WRITE_SINGLE_REG:     Result := 'Write Single Register';
    FUNC_WRITE_MULTIPLE_COILS: Result := 'Write Multiple Coils';
    FUNC_WRITE_MULTIPLE_REGS:  Result := 'Write Multiple Registers';
    FUNC_READ_WRITE_REGS:      Result := 'Read/Write Multiple Registers';
  else
    { Vendor-specific or reserved function codes in the range 65–72 and
      100–110 are valid Modbus but not defined here.  The hex code is shown
      so the user can identify them manually. }
    Result := Format('Unknown Function (0x%02X)', [AFunc]);
  end;
end;

{ =============================================================================
  GetExceptionName
  =============================================================================
  Maps a Modbus exception code byte to its standard description.
  Codes 0x01–0x0B are defined by the Modbus specification; codes 0x0C–0xFF
  are vendor-specific or reserved.

  Exception code table (Modbus Application Protocol V1.1b3, §7):
    01  Illegal Function          — FC not supported by the slave
    02  Illegal Data Address      — address out of range for this slave
    03  Illegal Data Value        — value in data field not allowed
    04  Server Device Failure     — unrecoverable error during execution
    05  Acknowledge               — long-running command accepted, poll later
    06  Server Device Busy        — slave busy processing a long command
    07  Negative Acknowledge      — slave cannot execute the program function
    08  Memory Parity Error       — slave detected a parity error in memory
    0A  Gateway Path Unavailable  — gateway misconfigured or overloaded
    0B  Gateway Target Device Failed — no response from target device       }
function GetExceptionName(ACode: Byte): string;
begin
  case ACode of
    $01: Result := 'Illegal Function';
    $02: Result := 'Illegal Data Address';
    $03: Result := 'Illegal Data Value';
    $04: Result := 'Server Device Failure';
    $05: Result := 'Acknowledge';
    $06: Result := 'Server Device Busy';
    $07: Result := 'Negative Acknowledge';
    $08: Result := 'Memory Parity Error';
    $0A: Result := 'Gateway Path Unavailable';
    $0B: Result := 'Gateway Target Device Failed';
  else
    Result := Format('Unknown Exception (0x%02X)', [ACode]);
  end;
end;

end.

